### ISSUE TITLE
[MySQL] AddSequencedLeaves occasionally deadlocks under load

### ISSUE THREAD

**Issue by pavelkalinnikov** [google/trillian#1096]
`YYY/MM/DD HH:MM:SS Failed to add batch starting at 44768: backend AddSequencedLeaves request failed: rpc error: code = Unknown desc = Error 1213: Deadlock found when trying to get lock; try restarting transaction
`

Presumably there is a conflict between `AddSequencedLeaves` and `LogSigner`'s tree integration loop.

Retry the transaction for some time with backoff policy in place?
Avoid the conflict in the first place?

**Comment by pavelkalinnikov** [comment]
```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2018-04-17 17:25:52 7f316b5a4b00
*** (1) TRANSACTION:
TRANSACTION 4443276, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 322 lock struct(s), heap size 46632, 319 row lock(s), undo log entries 508
MySQL thread id 729, OS thread handle 0x7f31623fdb00, query id 26981583 172.18.0.5 test update
INSERT INTO LeafData(TreeId,LeafIdentityHash,LeafValue,ExtraData,QueueTimestampNanos) VALUES(?,?,?,?,?)
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 26 page no 5595 n bits 72 index `PRIMARY` of table `test`.`LeafData` trx table locks 3 total table locks 2  trx id 4443276 lock_mode X insert intention waiting lock hold time 0 wait time before grant 0 
*** (2) TRANSACTION:
TRANSACTION 4443285, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
256 lock struct(s), heap size 30248, 253 row lock(s), undo log entries 408
MySQL thread id 736, OS thread handle 0x7f316b5a4b00, query id 26982580 172.18.0.5 test update
INSERT INTO LeafData(TreeId,LeafIdentityHash,LeafValue,ExtraData,QueueTimestampNanos) VALUES(?,?,?,?,?)
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 26 page no 5595 n bits 72 index `PRIMARY` of table `test`.`LeafData` trx table locks 3 total table locks 2  trx id 4443285 lock mode S lock hold time 0 wait time before grant 0 
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 26 page no 8086 n bits 72 index `PRIMARY` of table `test`.`LeafData` trx table locks 3 total table locks 2  trx id 4443285 lock_mode X insert intention waiting lock hold time 0 wait time before grant 0 
*** WE ROLL BACK TRANSACTION (2)

```

**Comment by pavelkalinnikov** [comment]
Not sure whether we can fully avoid such deadlocks. `AddSequencedLeaves` transaction inserts both to `LeafData` and `SequencedLeafData`, and these tables are keyed differently (`MerkleLeafHash` in one vs. `LeafIndex` in the other), so sorting according to one key deterministically makes the order of the other key indeterministic.

**Comment by pavelkalinnikov** [comment]
@Martin2112 @AlCutter Any ideas?

**Comment by Martin2112** [comment]
Not sure this is easy to fix. You can try getting locks early on the range of leaf indices that it's going to insert.

**Comment by pavelkalinnikov** [comment]
Since a single sorting order doesn't work, perhaps I could do both orderings: by `LeafIdentityHash` and by `LeafIndex` (no preprocessing needed for the latter as it's already sorted this way). Then acquire locks in `LeafData` in the order of `LeafIdentityHash`, and then run the current `INSERT`ing sequence.

Alternatively, as you say, we could pre-lock `SequencedLeafData` range (and thus optimize for the case where the leaves in `AddSequencedLeaves` are contiguous), perhaps it would be faster than N individual locking operations on `LeafData`?

**Comment by Martin2112** [comment]
You can try that first. The deadlock is on LeafData, which implies that deterministic ordering for that insert might be enough.

**Comment by Martin2112** [comment]
This is fixed I think?

**Comment by pavelkalinnikov** [comment]
Yup, haven't seen this problem after the fix.
