### ISSUE TITLE
./scripts/resetdb.sh appears to assume MySQL is on the default Unix socket

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1099]
The `README` (perhaps) ambiguously states that MySQL should

"listen on the standard MySQL port 3306 (so mysql --host=127.0.0.1 --port=3306 connects OK)". 

This appears incorrect.

The `./scripts/resetdb.sh` appears (not an expert) to assume that `mysqld` is running on the default TCP socket and fails if, as in my case, I have a remote Cloud SQL MySQL instance proxyied to 127.0.0.1:3306.

```
./scripts/resetdb.sh
Warning: about to destroy and reset database 'test'
Are you sure? [Y/N]: Y
Resetting DB...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
```

Whereas, I can happily:
```
docker run \
--interactive \
--tty \
--rm \
--net=host \
mysql mysql --host=127.0.0.1 --port=3306 --user=root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 152
Server version: 5.6.36-google (Google)
```

I jimmied the script to force it to use the port and it works. Unfortunately my bash fu is insufficient to understand the approach in the provided script and I'm unable to provide an elegant fix:
```
mysql "${FLAGS[@]}" --host=127.0.0.1 --port=3306 -e 
```

The integration tests (`./integration/integration_tests.sh`) don't appear to make this assumption (or they assume `localhost:3306`) and they proceed correctly.

Recommend:
-- Fix the `./scripts/resetdb.sh` to either not assume the server's location or permit specifying it

**Comment by AlCutter** [comment]
I _think_ the script as it stands would let you do:
```bash
./scripts/resetdb.sh --host=127.0.0.1 --port=3306
```
But we can update it to also allow specifying those things through ENV vars like the USER/DB ones too.

**Comment by DazWilkin** [comment]
Not from putting flags on the command-line because these are then duplicated|overriden:

```
./scripts/resetdb.sh --host=127.0.0.1
- Using MySQL Flags: --host=127.0.0.1 --user root --host localhost --port 3306
Warning: about to destroy and reset database 'test'
Are you sure? [Y/N]: Y
Resetting DB...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

```

but it does work if I set the environment:

```
DB_HOST=127.0.0.1 ./scripts/resetdb.sh --verbose
- Using MySQL Flags: --user root --host 127.0.0.1 --port 3306
Warning: about to destroy and reset database 'test'
Are you sure? [Y/N]: Y
Resetting DB...
Reset Complete
```
