### ISSUE TITLE
Map can become stuck due to partially applied update

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#1109]
Due to the multi-transactional nature of Trillian Map updates, it's possible for an update to be only partially applied.

For many storage implementations, this causes the map to get wedged because an application retrying the same update will attempt to re-write the same set of subtrees at the same revision which will fail.

**Comment by daviddrysdale** [comment]
Believe fixed:
 - storage idempotent on a repeat
 - API documents that client has to re-send the same request
