### ISSUE TITLE
Make it a bit easier to deploy Trillian onto GCE

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#1129]
Fix up scripts/k8s configs, improve docs etc.

**Comment by DazWilkin** [comment]
I would like to try to help with this activity as a way to build my understanding of Trillian.

I'm reasonably proficient with Kubernetes.

One advantage -- of course -- to focusing on Kubernetes, is that this facilitates running Trillian easily wherever Kubernetes runs; not just on GCE.

**Comment by AlCutter** [comment]
@DazWilkin Great, thanks!
@RJPercival on the team here is a good point of contact to coordinate with on this.

**Comment by DazWilkin** [comment]
I submitted a bunch of mostly loosely-coupled PRs:

https://github.com/google/trillian/pulls/dazwilkin

I will fork the repo and start making aggregate pulls.

-- reduced image sizes 1.2GB to 40MB
-- simplified images
-- replaced `curl` healthchecks with native http gets

One thing we may wish to consider is using Container Builder triggered on the repo to generate images automatically into Container Registry?

This would create "golden" images and save the duplicated effort of developers having to clone the repo, build and push images just to deploy.

**Comment by paulmattei** [comment]
New - Terraform / kubernetes / Cloud Spanner on gcp deployment code @

https://github.com/google/trillian/tree/master/deployment#kubernetes-on-gcp-using-cloud-spanner
