### ISSUE TITLE
If WaitForMastership fails log_signer sits around doing nothing

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#1150]
If the call to [`WaitForMastership` fails in `electionRunner.Run`](https://github.com/google/trillian/blob/a58c1a0253e92d7496de46a0950bd9b1ce128339/server/log_operation_manager.go#L150-L153) it returns from the function and sits around doing nothing for that log (i.e. `masterFor` calls will always return empty and nothing can be done). This can be triggered by recoverable intermittent etcd issues.

The `return` should either be replaced with `continue` (perhaps with a backoff?) when hitting errors from `WaitforMastership` or the `electionRunner` should be removed from `l.electionRunner[logID]` when it exits so a new election goroutine can be created the next time `masterFor` is called. I'd probably go for the first of the two options.

**Comment by pavelkalinnikov** [comment]
Hi Roland, thanks for filing this. I am working right now on factoring out the election runner, and also noticed this issue. I have a work-in-progress PR that largely interferes with this code. Would you like to review that?

**Comment by rolandshoemaker** [comment]
Ah cool, I'll take a look, thanks!

**Comment by Martin2112** [comment]
Did #1144 fix your issue?

**Comment by pavelkalinnikov** [comment]
No, that was a refactoring, and it ended up postponed.

**Comment by pavelkalinnikov** [comment]
This is effectively fixed now. Election code has migrated to [util/election](/util/election/) (types `Runner` and `MasterTracker`). If election fails at any step, it will be attempted again.

**Comment by pavelkalinnikov** [comment]
No, actually the problem seems to be still there: https://github.com/google/trillian/blob/85d73fd1e11bcca6a0bd2f2c6ef8409d5289dcd3/log/operation_manager.go#L242
