### ISSUE TITLE
log_server should return a typed error on out of range GetLeavesByIndex

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#1162]
When a GetLeavesByIndex request is a range that is > than the current tree size `log/mysql/log_storage.go` returns a `len(ret): %d, want %d` error. When piped back to CTFE this causes a 500 as thinks the RPC failed (which I guess it did...) instead of the more appropriate 404 (or 400).

I think there are two options here, return a typed error that CTFE can check against and return a special error in the case or do what CTFE currently thinks trillian does and return a non-error response and allow it to use the log root in the response to determine if the request was out of range. Probably the first makes more sense.

**Comment by Martin2112** [comment]
The cloud spanner log storage already does this so making the mysql code consistent seems the best approach.
