### ISSUE TITLE
Replace `curl` HEALTHCHECKs w/ Golang

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1165]
I remain confident that minimal container images would be a good thing for Trillian deployments.

https://github.com/google/trillian/pull/1155
https://github.com/google/trillian/pull/1154

However, I overlooked a dependency with Docker's HEALTHCHECKs and `curl`.

Thinking more about it today and some research, I have a working solution: Golang-based healthchecking.

This repo provides a solution:
https://github.com/Soluto/golang-docker-healthcheck-example

I tweaked it slightly to make it a drop-in replacement for the Trillian Dockerfiles:
https://gist.github.com/DazWilkin/d4fac48b810fb646384e2d422c81ac13

It can be folded into the multi-stage build, e.g. trillian_log_server:
```
FROM golang:1.10 as build

ADD . /go/src/github.com/google/trillian

WORKDIR /go/src/github.com/google/trillian

RUN go get ./server/trillian_log_server
RUN go get ./healthcheck

FROM gcr.io/distroless/base as runtime

COPY --from=build /go/bin/trillian_log_server /
COPY --from=build /go/bin/healthcheck /

ENV HTTP_PORT=8091

ENTRYPOINT ["/trillian_log_server"]

HEALTHCHECK \
  --interval=5m \
  --timeout=3s \
  CMD ["/healthcheck","http://localhost:$HTTP_PORT/debug/vars"]
```

The image size is reduced from 1.2GB-->45MB *and* -- beyond the [distroless/base](https://github.com/GoogleContainerTools/distroless) -- only includes binaries for `trillian_log_server` and `healthcheck`.

**Comment by daviddrysdale** [comment]
Is there a PR for this?

**Comment by DazWilkin** [comment]
No.

At the time, I had a backlog of PRs and decided to just note this here.

I've not made any contributions to Trillian since this time, remain interested in supporting the project but would need to take some time to regain context in order to create a PR.

**Comment by RJPercival** [comment]
We've ended up getting rid of the HEALTHCHECK directives from the Dockerfiles, in favour of configuring this at the docker-compose/Kubernetes level.
