### ISSUE TITLE
Error starting log_signer and log_server pods using Kubernetes deployment

### ISSUE THREAD

**Issue by paulmattei** [google/trillian#1176]
@DazWilkin 

Using the current deployment config I couldn't get the `trillian-logserver-deployment` or `trillian-logsigner-deployment` pods to launch successfully.

> Failed to pull image "gcr.io/iot-trust/log_server:latest": rpc error: code = Unknown desc = Error: Status 405 trying to pull repository iot-trust/log_server: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices"

The way I fixed this was to manually the add the `latest` tag to the containers in the Registry.

As a quick work around I removed the tag (git rev-parse HEAD) from the docker builds in deploy.sh which then by default added the `latest` tag

Events:
  Type     Reason                 Age               From                                                          Message
  ----     ------                 ----              ----                                                          -------
  Normal   Scheduled              1m                default-scheduler                                             Successfully assigned trillian-logserver-deployment-c4479cb97-2bxlk to gke-trillian-opensourc-logserver-pool-8edb5d96-70kk
  Normal   SuccessfulMountVolume  1m                kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  MountVolume.SetUp succeeded for volume "default-token-rht6d"
  Normal   SuccessfulMountVolume  1m                kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  MountVolume.SetUp succeeded for volume "google-cloud-key"
  Normal   Pulling                1m                kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  pulling image "gcr.io/google-containers/prometheus-to-sd:v0.2.6"
  Normal   Pulled                 1m                kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  Successfully pulled image "gcr.io/google-containers/prometheus-to-sd:v0.2.6"
  Normal   Created                1m                kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  Created container
  Normal   Started                1m                kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  Started container
  Normal   Pulling                42s (x3 over 1m)  kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  pulling image "gcr.io/iot-trust/log_server:latest"
  Warning  Failed                 42s (x3 over 1m)  kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  Failed to pull image "gcr.io/iot-trust/log_server:latest": rpc error: code = Unknown desc = Error: Status 405 trying to pull repository iot-trust/log_server: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices"
  Warning  FailedSync             15s (x8 over 1m)  kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  Error syncing pod
  Normal   BackOff                15s (x5 over 1m)  kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  Back-off pulling image "gcr.io/iot-trust/log_server:latest"

**Comment by DazWilkin** [comment]
Good catch!

I assume when these scripts were created, `latest` was tagged to images automatically.

It's not a good practice to use|assume `latest`.

A better approach is to apply `${TAG}` to the deployment files instead of `latest`.

I'll submit a PR.

**Comment by paulmattei** [comment]
Coo. Also FYI registry is actually already us.gcr.io in deploy.sh - it being gcr.io was me playing around.
