### ISSUE TITLE
Cannot write trillian service account key to stdout

### ISSUE THREAD

**Issue by paulmattei** [google/trillian#1179]
@DazWilkin 

Trillian key not being written to kubernetes secret by create.sh

When pod runs, error:

> Warning  FailedMount            16s (x13 over 10m)  kubelet, gke-trillian-opensourc-logserver-pool-8edb5d96-70kk  MountVolume.SetUp failed for volume "google-cloud-key" : secrets "trillian-key" not found

Tested:

`$ gcloud iam service-accounts keys create /dev/stdout --iam-account="trillian@${PROJECT_NAME}.iam.gserviceaccount.com" | kubectl create secret generic trillian-key --from-file=key.json=/dev/stdin`

> ERROR: (gcloud.iam.service-accounts.keys.create) Unable to write file [/dev/stdout]: [Errno 13] Permission denied: '/dev/stdout'

Some default permissions too restrictive on my mac?

Hacked around until fix found with:

```
gcloud iam service-accounts create trillian --display-name "Trillian service account"
gcloud iam service-accounts keys create /tmp/trillian-key --iam-account="trillian@${PROJECT_NAME}.iam.gserviceaccount.com"
kubectl create secret generic trillian-key --from-file=/tmp/trillian-key
rm /tmp/trillian-key
```

**Comment by DazWilkin** [comment]
That (Linux) trick is used elsewhere in the deployment (lines 42-45):
https://github.com/google/trillian/blob/9c0d0c07e9f5dee99b02ae2db7adef4ce03ac9d4/examples/deployment/kubernetes/deploy.sh#L42

Did those bork you too?

**Comment by paulmattei** [comment]
envsubst wasn't on the mac so had to `brew install gettext`

Then there is a warning:
```
Warning: gettext is keg-only and must be linked with --force
Note that doing so can interfere with building software.
```

Haven't looked into potential issues, so for now just using absolute path:

```
/usr/local/Cellar/gettext/0.19.8.1/bin/envsubst < examples/deployment/kubernetes/trillian-cloudspanner.yaml | kubectl create -f -

# Launch with kubernetes
/usr/local/Cellar/gettext/0.19.8.1/bin/envsubst < examples/deployment/kubernetes/trillian-log-deployment.yaml | kubectl apply -f -
/usr/local/Cellar/gettext/0.19.8.1/bin/envsubst < examples/deployment/kubernetes/trillian-log-service.yaml | kubectl apply -f -
/usr/local/Cellar/gettext/0.19.8.1/bin/envsubst < examples/deployment/kubernetes/trillian-log-signer-deployment.yaml | kubectl apply -f -
/usr/local/Cellar/gettext/0.19.8.1/bin/envsubst < examples/deployment/kubernetes/trillian-log-signer-service.yaml | kubectl apply -f -
```

**Comment by DazWilkin** [comment]
I'd not seen `envsubst` before trying Trillian's deployment.

It solves an annoying Kubernetes problem with how to parameterize YAML|JSON spec files.

Alternatives for us to consider, adopting either|both:
-- [Jsonnet](https://jsonnet.org/) (possibly Ksonnet) is a templating language (from Google)
-- Helm as a 'package manager'

**Comment by RJPercival** [comment]
The original problem of getting `permission denied: '/dev/stdout'` sounds like this: https://unix.stackexchange.com/a/38580. Were you by any chance using `su` or `sudo`?
