### ISSUE TITLE
Add Kubernetes' Namespace(s)?

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1184]
The Kubernetes deployments scripts do not currently support the use of Kubernetes namespaces. 

Namespaces are a good practice in partitioning workloads in Kubernetes clusters. Namespaces would, for example, permit the creation of dev, test, prod Trillian deployments in a single cluster.

Recommend: incorporating namespaces in the Kubernetes deployment scripts.

**Comment by RJPercival** [comment]
Fixed by PR #1184.
