### ISSUE TITLE
Kubernetes `create.sh` does not await Node Pool creation

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1185]
https://github.com/google/trillian/blob/9c0d0c07e9f5dee99b02ae2db7adef4ce03ac9d4/examples/deployment/kubernetes/create.sh#L60

The Kubernetes `create.sh` script provisions a Kubernetes cluster, node pools (see https://github.com/google/trillian/issues/1183) and an etcd cluster. Many of the cluster creation operations proceed asynchronously and the script fails on creation of the etcd cluster if the cluster is not completely provisioned (== nearly always).

`gcloud container node-pools create` is async but does not appear to provide an await or async (operation) that could be monitored for successful creation of the node pools in order to block the etcd operation deployment.

Recommend:
-- temporarily inject long-sleep into the script to give sufficient time to provision the cluster before attempting to deploy the etcd operator;
-- identify ways to wait on the operations underlying the node pools create

**Comment by Martin2112** [comment]
I believe this can be closed?

**Comment by DazWilkin** [comment]
I think so. I've not revisited Trillian since this time.

**Comment by RJPercival** [comment]
This would be fixed by PR https://github.com/google/trillian/pull/1181, but that seems to have stalled.

**Comment by RJPercival** [comment]
Node pools were removed by PR #1312.
