### ISSUE TITLE
Support watch-based master election implementations

### ISSUE THREAD

**Issue by pavelkalinnikov** [google/trillian#1191]
The current implementation of master election polls mastership status using `MasterElection.IsMaster` interface every now and then (`MasterCheckInterval`). The downside of such approach is weak guarantees on what's been happening between `IsMaster` calls, plus a bit of excess `etcd` traffic.

`etcd` has an alternative watch-based solution for [observing](https://github.com/coreos/etcd/blob/438e6750ee4dd3861c83514e405adf2f3e437e4c/clientv3/concurrency/election.go#L158) mastership changes (gRPC stream inside). Perhaps we could refactor the election API to support such mechanisms as well.

**Comment by pavelkalinnikov** [comment]
I can see this as some `GetMasterContext` method which is a bit like `WaitForMastership` but also returning a `context.Context` which is active as long as the instance is the master. In `etcd` implementation it would spin up the watcher internally, and close the returned context as soon as the mastership / connectivity is lost. `MasterElection` implementations that don't have passive watching mechanisms could do the old busy waiting to emulate `GetMasterContext` (something like the code in #1177).

**Comment by pavelkalinnikov** [comment]
@AlCutter @daviddrysdale WDYT?

**Comment by AlCutter** [comment]
Sounds pretty neat on the face of it, I like the `Context` idea.
Any thoughts from @pphaneuf too?

**Comment by pavelkalinnikov** [comment]
A prototype is here: https://github.com/google/certificate-transparency-go/pull/268

**Comment by pavelkalinnikov** [comment]
Followed by https://github.com/google/certificate-transparency-go/pull/279

**Comment by pavelkalinnikov** [comment]
At some point we may need an interface allowing to contact the current master (in a way similar to #1139), for example if we want to submit entries directly through the `logsigner` to improve latency. The right way to do it would probably be having a separate "observer" interface that doesn't participate in master election, only observes it.

**Comment by pavelkalinnikov** [comment]
This has been fixed a while ago when `election2` package replaced the old one.
