### ISSUE TITLE
Are foreign key constraints in SQL schema needed?

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#1216]
Comparing the cloud spanner schema to the SQL one I notice that the spanner one doesn't have any foreign key constraints (although I think spanner doesn't really have this concept?). Are we relying on these constraints for any consistency/safety guarantees or are most of these safety checks in code?

I ask because due to codership/galera#491 we are still unable to do multi-master writes in the SQL world and _I think_ we could work around that issue by simply ripping out all of the foreign key constraints (probably, still need to do some more testing).

**Comment by Martin2112** [comment]
CloudSpanner doesn't really have foreign keys. See interleaving in https://cloud.google.com/spanner/docs/schema-and-data-model, however there are data size restrictions on it that make it not really work for us atm.

I don't think I can give any guarantees that it won't cause problems. One risk is that it allows a bug to insert incorrect data that would currently be blocked before it could make the log inconsistent.

OTOH we're not totally relying on these for consistency the primary keys that prevent inserting the same tree subtree version from two signers would still block this.

I think it's partly down to your approach to risk and how much confidence we have in testing / CI catching issues.

**Comment by Martin2112** [comment]
I'll close this for now. Please reopen if there are more questions.
