### ISSUE TITLE
./scripts/resetdb.sh error

### ISSUE THREAD

**Issue by ricketybridge** [google/trillian#1229]
I followed the directions in regards to setting up Trillian (including ensuring that a MySQL instance was running), and `./scripts/resetdb.sh` resulted in this:

```
Warning: about to destroy and reset database 'test'
Are you sure? [Y/N]: Y
Resetting DB...
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'zaphod'' at line 1
```

**Comment by daviddrysdale** [comment]
That sounds like a MySQL version problem -- what version do you have installed locally?

(Our [CI system uses 5.6.x](https://docs.travis-ci.com/user/database-setup/#MySQL), and I run locally with a 5.7.x version, so I'm guessing you've got neither of those.)

**Comment by ricketybridge** [comment]
I was using 8.0 (??) since I'm on MacOS and that's the latest version via brew. I uninstalled it and tried to install 5.7, but I'm having serious issues with it for some reason.
