### ISSUE TITLE
Unknown table 'test.trees' etc.

### ISSUE THREAD

**Issue by ricketybridge** [google/trillian#1234]
Running `./scripts/resetdb.sh` for a second time (or `./integration/integration_test.sh` after running `./scripts/resetdb.sh`) gives me this error:

```
Warning: about to destroy and reset database 'test'
Are you sure? [Y/N]: Y
Resetting DB...
ERROR 1051 (42S02) at line 1: Unknown table 'test.trees,test.mapleaf,test.treecontrol,test.maphead,test.sequencedleafdata,test.treehead,test.leaf'
```

It happens with fresh installs of both MySQL 5.6 and 5.7. I'm using Go 10.3 on MacOS.

I then tried to drop the `test` database manually on the command line, only to get the same error.

**Comment by Martin2112** [comment]
Are you sure your database is correctly installed and not corrupted? Did you perhaps run out of disk space at some point for example?

**Comment by ricketybridge** [comment]
I mean, it happens immediately after running `./scripts/resetdb.sh`, which creates the database, and even when I haven't touched or added anything to the database at all. AFAICT, I was far from running out of disk space, and that MySQL is installed correctly.

**Comment by Martin2112** [comment]
At a mysql command prompt you type `DROP DATABASE test;` and you get a 1051 error? Can you upload the mysql server log file?

**Comment by ricketybridge** [comment]
Yes: 

```
mysql> drop database test;
ERROR 1051 (42S02): Unknown table 'test.trees,test.mapleaf,test.treecontrol,test.maphead,test.sequencedleafdata,test.treehead,test.leaf'
mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+-------------------+
| Tables_in_test    |
+-------------------+
| LeafData          |
| MapHead           |
| MapLeaf           |
| SequencedLeafData |
| Subtree           |
| TreeControl       |
| TreeHead          |
| Trees             |
| Unsequenced       |
+-------------------+
9 rows in set (0.00 sec)
```

Log attached.

[mysql_log.txt](https://github.com/google/trillian/files/2267363/mysql_log.txt)

**Comment by Martin2112** [comment]
Hi. I don't know what the cause is but your database is in a corrupt / damaged state.

```
2018-07-25T18:23:11.156607Z 47 [ERROR] InnoDB: Table `test`.`trees` does not exist in the InnoDB internal data dictionary though MySQL is trying to drop it. Have you copied the .frm file of the table to the MySQL database directory from another database? Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-troubleshooting.html for how to resolve the issue.
```

I suggest you completely uninstall it and delete everything in the mysql data directory before reinstalling.
