### ISSUE TITLE
Local deployment using docker-compose fails

### ISSUE THREAD

**Issue by CosmicCoder96** [google/trillian#1263]
Operating system: Ubuntu 16

Steps followed:
As mentioned here for `local deployment`:
https://github.com/google/trillian/tree/master/examples/deployment

Relevant Error on console:

```
trillian-log-server_1  | F0827 14:20:15.573541       1 main.go:100] Failed to get storage provider: dial tcp 127.0.0.1:3306: connect: connection refused
trillian-log-server_1  | F0827 14:20:16.809797       1 main.go:100] Failed to get storage provider: dial tcp 127.0.0.1:3306: connect: connection refused
trillian-log-server_1  | F0827 14:20:17.988925       1 main.go:100] Failed to get storage provider: dial tcp 127.0.0.1:3306: connect: connection refused
trillian-log-signer_1  | F0827 14:20:13.281327       1 main.go:92] Failed to get storage provider: dial tcp 127.0.0.1:3306: connect: connection refused
trillian-log-signer_1  | F0827 14:20:14.520931       1 main.go:92] Failed to get storage provider: dial tcp 127.0.0.1:3306: connect: connection refused
```

Complete log:
[output.txt](https://github.com/google/trillian/files/2324216/output.txt)

**Comment by RJPercival** [comment]
Our [docker-compose.yml](https://github.com/google/trillian/blob/master/examples/deployment/docker-compose.yml) file has rotted and no longer works for the following reasons:
- The `DB_HOST` environment variable is not provided to ./scripts/resetdb.sh to tell it to connect to the MySQL server running in the "mysql" container.
- The `--mysql_uri` flag is not provided to trillian_log_server or trillian_log_signer to tell them to connect to the MySQL server running in the "mysql" container.
- ./scripts/resetdb.sh creates a "test" user for Trillian to use that can only be connected to from localhost, so even with the above environment variable and flags, the database connection will fail.

We could either undertake the work required to fix this, or we could drop support for [Docker Compose](https://docs.docker.com/compose/). Arguments for maintaining support are:
- It would be one of the simplest ways to get a test deployment of Trillian running locally (no Kubernetes cluster required).
- It makes it easy to see how components of the Trillian system fit together.

Arguments against are:
- It's another thing to maintain.
- We don't typically use it ourselves.
- It will only be suitable for test deployments.
