### ISSUE TITLE
Go 1.11 tools use $GOFLAGS automatically

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#1276]
[Our Travis config](https://github.com/google/trillian/blob/master/.travis.yml) uses an environment variable called $GOFLAGS to store the flags to pass to some Go commands it uses, e.g. https://github.com/google/trillian/blob/39f3d280979a3be04b05418e7920f2c324e94182/.travis.yml#L66  
[Go 1.11 will read the $GOFLAGS variable itself](https://github.com/golang/go/issues/27282) so we won't need to use it as part of any commands. This will, however, possibly result in other `go` commands we use getting these flags where previously they didn't.

**Comment by daviddrysdale** [comment]
(Nothing to do until we move our Travis builds to use Go 1.11)

**Comment by daviddrysdale** [comment]
Also: gometalinter [fixed upstream](https://github.com/alecthomas/gometalinter/commit/8edca99e8a88355e29f550113bcba6ecfa39ae11) for this.
