### ISSUE TITLE
HTTP API is untested

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#1279]
Trillian offers a HTTP API that is auto-generated (with the help of some annotations) from our RPC API, e.g. 
https://github.com/google/trillian/blob/670a91ca44c098055e1cf5339708e5e7e026f654/trillian_log_api.proto#L37-L42

However, we do not test it or use it ourselves, so its reliability and usability are unknown. We should either properly support it or remove it.

**Comment by gdbelvin** [comment]
Let's move these HTTP APIs to a personality example
