### ISSUE TITLE
MySQL storage: Add flag for max connections

### ISSUE THREAD

**Issue by jsha** [google/trillian#1285]
When using the MySQL backend, it's important to limit the number of connections per log_server and log_signer. Otherwise, during peak traffic, log_server will hit the MySQL server-side connection limit, effectively locking out log_signer from making new connections. This causes sequencing to halt, which quickly creates enough of a backlog that log_server has to start returning errors on submissions.

**Comment by jsha** [comment]
In #722 and #1288 there was some conversation about whether limiting the DB connections is the right move. Let's concentrate that discussion here rather than the two PRs.

In my opinion, having operated https://github.com/letsencrypt/boulder/ for three years, setting a client-side connection limit is essential for safe operation of a Go service.

Go will automatically increase the size of its connection pool without limit if there is no connection immediately available when a new query is executed. This is true regardless of query type: SELECT, INSERT, etc. If any given client, or the sum of all clients, hits MySQL's server-side connection limit, all new connections will immediately receive `Error 1040: Too many connections`. Typically this will result in an error served to the user.

If, instead, a client-side limit is reached, the Go database driver will block until either a connection is available or the context is canceled. During brief spikes, this means latency may increase slightly, but the service is less likely to serve errors. In other words, client-side limits allow a service to degrade gracefully rather than fail abruptly under load.

Worse, in Trillian's case, we found that `log_server` can consume all of MySQL's server-side connection limit, starving `log_signer`. In particular this happened to us recently on a test log. There was a `log_signer` election during a period of peak load. The new `log_signer` did not have any open connections because it had been previously idle. It was unable to make a new connection because `log_server` was consuming all of the server-side limit while processing new submissions from `ct_server`. As a result, all sequencing halted. Not long after, all submissions started failing because the unsequenced queue had grown too large. This caused a significant outage, which is at least the second outage we've had related to database connection limits.

In Boulder we solve this by making sure each client has a client-side limit set so that it can't starve other database users. This has worked very well for us.

The argument in #722 was that this issue should be solved by rate limits. I think both are needed. Database connections are a specific, internal resource, and do not clearly map to requests per second. For instance, the number needed depends sensitively on the duration of each database query. And the number of database requests made per action may change as the software involves. I think it's important to set safety rails on critical internal resources like this.

**Comment by jsha** [comment]
@daviddrysdale @Martin2112 I know I just filed this yesterday, but if you can find time for a quick discussion here it would save a lot of pain for my operations team, which has been getting paged due to log outages related to this.

If there is another group out there running a high traffic MySQL-backed Trillian log, I'd definitely be interested in hearing how they manage these issues.

Thanks,
Jacob

**Comment by daviddrysdale** [comment]
Well, if this is going to help you in the short term, how about we prevaricate about the bush?  Add the flag but have a default value that does nothing:
```golang
if mySQLMaxConns > 0 {
  db.SetMaxOpenConns(mySQLMaxConns)
}
```
That way you can set it to get the behaviour you want without affecting other deployments, and we can discuss the best overall approach separately.

WDYT?
