### ISSUE TITLE
See if there's a better mechanism for the SQL building in MySQL/PGSQL storage implementations.

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#1369]
The string building and replacements are kinda scary from an SQL injection PoV, see comments in #1343.

Can this be replaced with something safer?

**Comment by Martin2112** [comment]
Not sure how big the risk is. The expansion just inserts a variable number of '?' placeholders, which are then used to bind parameters to.

If there's an example where this isn't the case I'll have a look at it.
