### ISSUE TITLE
[monitoring/prometheus] No separator between MetricFactory.Prefix and metric names

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1376]
If not intentional (developer provides separator if wanted), consider inserting a separator here:

https://github.com/google/trillian/blob/d4bf59f2deea12880cbee25d839e2d7ed473c07b/monitoring/prometheus/metrics.go#L39
https://github.com/google/trillian/blob/d4bf59f2deea12880cbee25d839e2d7ed473c07b/monitoring/prometheus/metrics.go#L61
https://github.com/google/trillian/blob/d4bf59f2deea12880cbee25d839e2d7ed473c07b/monitoring/prometheus/metrics.go#L97

Perhaps simply:
`Name: pmf.Prefix + "_" + name`

Avoids e.g.:
```
# HELP someprefixmysql_queue_leaf_latency_entry Latency of insert-entry part of queue (single) leaf operation in seconds
# TYPE someprefixmysql_queue_leaf_latency_entry histogram
```

With:
```
# HELP someprefix_mysql_queue_leaf_latency_entry Latency of insert-entry part of queue (single) leaf operation in seconds
# TYPE someprefix_mysql_queue_leaf_latency_entry histogram
```

I've written a simple OpenCensus monitoring example. I'd used "`[namespace]/[metric]`" because I have been testing with Stackdriver monitoring but realize this is a poor assumption and should probably use "`_`" there too. Will be consistent with this Prometheus implementation.

**Comment by RJPercival** [comment]
I believe it was intentional, i.e. the developer is expected to end their prefix with a separator if desired. We should probably document that `Prefix` variable though, to state that explicitly.
