### ISSUE TITLE
Standardize Server Skew Behavior

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#1472]
When making a trillian request with `first_tree_size` > `SLR` the server should
1. *Proposal* Return a canonical gRPC error of `Unavailable`, perhaps `WithDetails` describing the latest known SLR. 
1. *GetLatestSignedLogRoot* returns a simple gRPC `InvalidArgument` error, allowing clients to correctly deduce that something has gone wrong. 
1. *GetInclusionProofByHash* returns gRPC `OK` with an extra `SLR` response field set. 

Requirements , Requests, and Observations:
- gRPC errors allow clients to figure out if their requests have failed in a standardized way. 
- When erroring clients should avoid making a second RPC to discover what would have made for a valid request. 
- Clients have no guarantee about whether the `first_tree_size` they request will be on the server. 
- Once a client has rolled forward to a tree_size via a consistency proofs, it is invalid for clients to go backward. The client's only correct recourse is to retry until it reaches a server with an SLR >= to the tree_size observed by the client.  Any other behavior is evidence of forking.

**Comment by RJPercival** [comment]
I believe @benlaurie proposed and implemented the skew behaviour, so he may have comments on this.

**Comment by benlaurie** [comment]
I share the goal of not requiring a second RPC - indeed, this is a must or you may never converge.

I am unsure what `first_tree_size` is?

Not sure about the final bullet - going backwards is fine in terms of checking proofs and stuff, surely? In short, a client should always maintain the latest SLR (when did these stop being STHes, btw?) but can and should always validate any previously unseen SLRs against that one, always retaining the more recent...

**Comment by gdbelvin** [comment]
Consistency proofs are defined in terms of `first_tree_size` and `second_tree_size`.

**Comment by benlaurie** [comment]
Ah, OK. So you are specifically talking about consistency proofs? But you mention inclusion proofs, which presumably only have one tree eize?

So, my suggestion would be that:

a) Whatever happens, clients should be able to tell unambiguously that `(first_,second_,)tree_size`is > SLR.

b) Clients should always be told the latest SLR that is available (not just the size, the whole SLR).

c) Where appropriate, proof should also be returned using the latest SLR.

If there are concerns about wasted bandwidth, then clients could set flags turning off the supplementary info if they're not going to use it...

**Comment by Martin2112** [comment]
I'd like to avoid unnecessary changes to the current behaviour as well.

Returning an SLR is cheap. Proofs are relatively expensive and should not be returned without a clear indication that they're going to be used.

**Comment by benlaurie** [comment]
Sure, the flags can be either way up!

**Comment by gdbelvin** [comment]
The APIs involved are:

1. GetInclusionProof(index, tree_size)
1. GetInclusionProofByHash(hash, tree_size) 
1. GetConsistencyProof(first_tree_size, second_tree_size) 
1. GetLatestSignedLogRoot(*first_tree_size*)
1. GetEntryAndProof(index, tree_size)

**Comment by gdbelvin** [comment]
The APIs involved are:

1. GetInclusionProof(index, tree_size)
1. GetInclusionProofByHash(hash, tree_size) 
1. GetConsistencyProof(first_tree_size, second_tree_size) 
1. GetLatestSignedLogRoot(*first_tree_size*)
1. GetEntryAndProof(index, tree_size)
