### ISSUE TITLE
Tests do not clean up temporary database

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#1591]
If I connect to my local MySQL server and run `SHOW DATABASES;`, I see over 500 databases, each named something like "trl_1557738186819510061". It appears that one or more tests are not cleaning up the temporary database(s) they create.

**Comment by RJPercival** [comment]
For anyone wanting to delete these databases, the following command should work (though you may need to change the username and/or add "-p" to the mysql commands, depending on your server authentication):
```shell
$ mysql -uroot -e "SHOW DATABASES LIKE 'trl_%'" --batch | tail -n +2 | xargs -I "@@" echo "DROP DATABASE @@;" | mysql -uroot
```

**Comment by pavelkalinnikov** [comment]
Same issue on my machine. Last time I observed this it was less than 500 DBs, but I think this number increases each time you run tests.
