### ISSUE TITLE
Document admin functions

### ISSUE THREAD

**Issue by mhutchinson** [google/trillian#1660]
I can't see any documentation in the repo for how to go about creating a new tree.

The preferred mechanism to create & init a tree is now:

go run cmd/createtree/main.go --admin_server=${ADMIN_SERVER}

This isn't mentioned in any documentation. The closest we have is a pointer to https://medium.com/google-cloud/trillian-on-google-cloud-platform-621a37f2431c which does this the legacy way involving curl. This is also the same mechanism used by trillian/examples/deployment/kubernetes/provision_tree.sh

Doing this via curl can lead to trees being created but not initialized, which isn't a well trodden path.

**Comment by AlCutter** [comment]
This will be rolled up into #1357
