### ISSUE TITLE
Create Database Integration Test Suite

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#1740]
Each database implementation has its own set of "unit tests" 
We should really be testing these implementations at the interface layer so we can have some confidence that the assumptions we have about one storage implementation carry to the other implementations

**Comment by gdbelvin** [comment]
The storage integration test has revealed an interesting edge case. 

Here's the cloud spanner [documentation](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.Spanner.Commit):

> Commit might return an ABORTED error. This can occur at any time; commonly, the cause is conflicts with concurrent transactions. However, it can also happen for a variety of other reasons. If Commit returns ABORTED, the caller should re-attempt the transaction from the beginning, re-using the same session.

There are a new instances of 
```
	err := admin.ReadWriteTransaction(ctx, func(ctx context.Context, tx AdminTX) error {
```
That do not retry on `ABORTED`. 
These should probably be moved to `RunInAdminSnapshot` or `RunInTransaction`. 
`RunInX` should also be modified to retry on `ABORTED` errors.

**Comment by gdbelvin** [comment]
@AlCutter for cloud spanner API comments

**Comment by gdbelvin** [comment]
Implementation ongoing:
#2134 
#2133 
#2132

**Comment by gdbelvin** [comment]
Working cloudspanner :-D 
cc: @AlCutter @rmhrisk

**Comment by rmhrisk** [comment]
Woot woot ;)

**Comment by mhutchinson** [comment]
@pavelkalinnikov do you have any context on what work is remaining here?

**Comment by pavelkalinnikov** [comment]
`integration/storagetest` contains generic tests that can be used to test any storage implementation. If I remember correctly, it works for the storages in this repos, and what was left is making it work for our internal storage implementation. We can track it internally though.
