### ISSUE TITLE
Bump uber/prototool module to v1.8.1+ when they do another release

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#1756]
The v1.8.0 tag on github.com/uber/prototool was moved after the golang proxy had seen it, causing hash mismatch breakage:

```console
$ go mod download github.com/uber/prototool@v1.8.0
---- 8< --- snip --- 8< ----
verifying github.com/uber/prototool@v1.8.0: checksum mismatch
downloaded: h1:goRKXNdLz420vcXR5udSff/RUKXcL8B57FATe0u8uSs=
go.sum:     h1:AByDUuTG5nphja3+APWR04YPUjp7Ac0fZp/St1RKHlY=
```

For now we'll try to pin to the equivalent commit, but we'll want to manually update our dep to the next tagged release.

**Comment by paulmattei** [comment]
Uber did another release.
