### ISSUE TITLE
Improve CI monitoring

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#1772]
We only have minimal automated monitoring of our CI environment at the moment, via Stackdriver uptime checks. We should add monitoring using the metrics exported by our jobs, as well as taking advantage of other metrics provided by services we use (e.g. Cloud Spanner). This will help us to spot problems that do not cause the uptime check to fail.

**Comment by RJPercival** [comment]
I've configured some alerts for when containers restart frequently and when Trillian log server latency increases by at least 50% (a fairly loose threshold for now, to avoid false positives). These notifications will arrive on the Slack #dev channel and via email.

**Comment by pavelkalinnikov** [comment]
@AlCutter Is this still applicable? Or, given that you in the process of migrating to a different CI, it is obsolete?

**Comment by AlCutter** [comment]
Discussed with some folks on the team; this environment is not currently providing as much value as it could, to avoid confusion we'll turn it down for now. If there's a path to it providing the value that it _could_ this can be revisited.
