### ISSUE TITLE
Client controlled TreeID in CreateTree

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#1775]
`CreateTree` currently allows the caller to set private keys and control all other sources of randomness other than the TreeID. 

Because TreeID is part of the CONIKS hasher, not controlling the TreeID is producing a cascading avalanche of changes between multiple runs of the same test. 
TreeID -> MapLeafHash -> MapRoot -> LogLeaf -> LogRootHash. 

Generating repeatable test vectors has a lot of value in making the diffs between test vectors human readable.

**Comment by gdbelvin** [comment]
To enforce the random nature of client ID's, have the request be a `TreeIDPreimage`.

**Comment by pavelkalinnikov** [comment]
Closing this in favour of #2284. For logs this doesn't seem necessary, because `TreeID` is not accounted for in hashers.
