### ISSUE TITLE
golangci-lint dependency on go-critic issue w/ golang 1.13 (works w/ <=golang:1.12.7)

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1786]
Heads-up

```bash
Step #0: Pulling image: golang:1.13-rc-buster
Step #0: Digest: sha256:90c836736aff2a2fef8ad80240d2c40eb256d705c71b2cffbd502faab2bf61ea
Step #0: Status: Downloaded newer image for golang:1.13-rc-buster
Step #0: go: github.com/google/trillian@v1.3.0 requires
Step #0: 	github.com/golangci/golangci-lint@v1.17.2-0.20190630074125-360a58dca92d requires
Step #0: 	github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540: reading https://proxy.golang.org/github.com/go-critic/go-critic/@v/v0.0.0-20181204210945-1df300866540.mod: 410 Gone
Finished Step #0
ERROR
ERROR: build step 0 "golang:1.13-rc-buster" failed: exit status 1
```
Appears to be addressed by:
https://github.com/golangci/golangci-lint/pull/605

The issue does not appear to arise with Golang versions <=1.12.7

**Comment by DazWilkin** [comment]
The issues appear to be related to the proxy (and not Trillian or its dependencies); I'm using Cloud Build and, reading some of the commits on here, I reverted to `GOPROXY=direct` and everything now builds.

Filed: https://github.com/golang/go/issues/33530

**Comment by bcmills** [comment]
These are real issues exposed by the fact that the proxy is now using `go1.13beta1`. See https://tip.golang.org/doc/go1.13#version-validation.
