### ISSUE TITLE
Verify proofs before returning them

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#1787]
Trillian's API handlers that return proofs should verify them before returning them. This would allow Trillian to detect data corruption before exposing it to clients. Ideally, it would expose a metric that allowed for alerting when data corruption of this kind is detected.

**Comment by mhutchinson** [comment]
@gdbelvin and I have talked about this before. There are a few ways to do this. Some dimensions for consideration:
- When? Do this work inline or async?
- Where? In this task or have another server that is responsible for performing this
  - If another server: transparent proxy, or a server that is delegated to?
- How much? All traffic, or is sampling good enough?

**Comment by RJPercival** [comment]
![Trillian Proof Verification](https://user-images.githubusercontent.com/1949076/62703817-f0307b00-b9e1-11e9-9fc7-2ff513be76a5.png)

**Comment by mhutchinson** [comment]
Nice graph! For clarity, what is the proposed return in the sync case where an invalid proof is detected?

**Comment by RJPercival** [comment]
I was thinking an `INTERNAL` error, since this should only happen if there's something very wrong internally.

**Comment by pavelkalinnikov** [comment]
This feels like a nice feature, but it could be done in a personality. Making it integral in Trillian may inflict unwanted performance impact. Alternatively, it can be made configurable, which increases the overall complexity of Trillian.

Realistically, we are not planning to work on this shortly.
