### ISSUE TITLE
"etcdclusters.etcd.database.coreos.com" not found when running create.sh

### ISSUE THREAD

**Issue by tweksteen** [google/trillian#1820]
Following the steps from https://github.com/google/trillian/tree/master/examples/deployment/kubernetes/README.md, the create.sh scripts ends with:
```
[...]
clusterrolebinding.rbac.authorization.k8s.io/etcd-cluster-admin-binding created
clusterrolebinding.rbac.authorization.k8s.io/etcd-operator created
clusterrole.rbac.authorization.k8s.io/etcd-operator created
deployment.extensions/trillian-etcd-operator created
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "etcdclusters.etcd.database.coreos.com" not found
```

This might be more a warning than an error, as I am able to continue with the next steps.

**Comment by paulmattei** [comment]
Expected. Documented in Deployment [Readme](https://github.com/google/trillian/blob/master/deployment/README.md)

More info:
https://github.com/google/trillian/pull/1962#discussion_r353918274
