### ISSUE TITLE
Rust 

### ISSUE THREAD

**Issue by Alakazam03** [google/trillian#1885]
I am developing an application in rust. I want to use sparse merkle trees but i could not find any suitable library.

I want to use google/trillian. Is there any way i could use it?

**Comment by RJPercival** [comment]
Would it be sufficient to run Trillian and communicate with it via gRPC in order to outsource handling of the Merkle tree? I'm not aware of any more direct interop between Rust and Go.

**Comment by Alakazam03** [comment]
That should work nut there is a client that connects using Pypiclient but it does not have full functionality. 
My end goal is to have a sparse Merkle tree inaccessible to my rust service where can I store data, generate proof and verify proof.
I have tried various packages and raise issue also https://github.com/arnaucube/merkletree-rs/issues/1.

Sorry If I am asking any silly question, I am new to rust. @RJPercival

**Comment by RJPercival** [comment]
I'm afraid we don't have any experience with using Trillian from Rust. This blog post about the PyPi Transparency client might be helpful: https://pretired.dazwilkin.com/posts/190930/. However, if it's a spare Merkle tree you need (aka. Trillian's Map), then you'll probably need to write your own client. You should also bear in mind that the Map mode in Trillian is currently experimental.

**Comment by Alakazam03** [comment]
Hi sorry for newbie questions. I found you have a terraform aws trillian service deployment. Is there any way I can use that from rust? @RJPercival
