### ISSUE TITLE
storage/mysql: GetLeavesByIndex, getLeavesByRangeInternal, and getLeavesByHashInternal ignore row errors

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#1917]
The usages of `QueryContext` in `GetLeavesByIndex`, `getLeavesByRangeInternal`, and `getLeavesByHashInternal` do not check for a `rows.Err` after iterating over the rows returned by the query.

This causes a handful of issues, mainly if a context expires while rows are being read an incomplete set of rows is returned without a `deadline exceeded` error. `GetLeavesByIndex` catches this with a `want/got` check, but this is still rather confusing as it doesn't indicate _why_ this happened.

**Comment by pgporada** [comment]
When the timeout happens it resembles this
```
"W1017 05:44:53.778028       1 handlers.go:190] 2019{1234123412341234123}: GetEntries handler error: backend GetLeavesByIndex request failed: rpc error: code = Internal desc = len(ret): 509, want 512"
```
