### ISSUE TITLE
k8s deployment API is exposed by default

### ISSUE THREAD

**Issue by tweksteen** [google/trillian#1921]
Opposite to what is described in https://github.com/google/trillian/tree/master/examples/deployment/kubernetes#process:

> NOTE: none of the Trillian APIs are exposed to the internet with this config, this is intentional since the only access to Trillian should be via a personality layer.

The `trillian-log-service` and `trillian-log-signer` services are exposed to the internet because using the LoadBalancer type:
https://github.com/google/trillian/blob/master/examples/deployment/kubernetes/trillian-log-service.yaml
https://github.com/google/trillian/blob/master/examples/deployment/kubernetes/trillian-log-signer-service.yaml

Either this warning should be removed from the README or the type of service changed to ClusterIP or NodePort.

**Comment by RJPercival** [comment]
The `cloud.google.com/load-balancer-type: "Internal"` annotation means that the load balancer is only accessible from within your Cloud project, so long as you're using Google Cloud (which is what those instructions are for).

**Comment by tweksteen** [comment]
Right, I missed that annotation. Thanks!
