### ISSUE TITLE
Remove Registry Object

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#1994]
The Registry object contains the superset of configuration options between the Log, LogSigner, and the Map.  This makes it confusing and dangerous to construct since nil pointers will only be caught at runtime. 

Suggestion: 
Replace the registry object with direct objects in the constructors.

**Comment by pavelkalinnikov** [comment]
Maybe the registry object needs to be split accordingly. I'm not sure whether the direct parameters approach is better, for compatibility reasons (what if we need to add another optional parameter at some point?).

**Comment by gdbelvin** [comment]
https://github.com/google/wire might be an interesting idea for this
