### ISSUE TITLE
Consider deleting util/etcd/client.go

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#2021]
The documentation in this file says:
```
// TODO(pavelkalinnikov): Remove this when there is a way to compatibly import  
// the same version of etcd in external codebases. Could Go modules help? 
```
We are now using Go Modules, which suggests that we may now be able to delete the file. The documentation also refers to the "Trillian vendor/ directory" that no longer exists, which further suggests that the code may be obsolete.

**Comment by gdbelvin** [comment]
Consider upgrading to etcd 3.4, which supports go modules?
https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md
