### ISSUE TITLE
Getting error while building the image

### ISSUE THREAD

**Issue by Keerthana-Jayakumaran** [google/trillian#2084]
Hi,
when i ran the command "docker-compose -f examples/deployment/docker-compose.yml up",
I got error as these results,

Building trillian-log-signer
Step 1/14 : FROM golang:1.11 as build
 ---> 43a154fee764
Step 2/14 : WORKDIR /trillian
 ---> Using cache
 ---> ddea8aaa4d53
Step 3/14 : ARG GOFLAGS=""
 ---> Using cache
 ---> dbda66be6f2a
Step 4/14 : ENV GOFLAGS=$GOFLAGS
 ---> Using cache
 ---> f32708958c0c
Step 5/14 : ENV GO111MODULE=on
 ---> Using cache
 ---> a977766fe264
Step 6/14 : COPY go.mod go.sum ./
 ---> Using cache
 ---> 1ab907f636ca
Step 7/14 : RUN go mod download
 ---> Using cache
 ---> 49275a7b42e2
Step 8/14 : COPY . .
 ---> Using cache
 ---> 542203d606ea
Step 9/14 : RUN go get ./cmd/trillian_log_signer
 ---> Using cache
 ---> 06ebd790b760
Step 10/14 : RUN go run github.com/google/go-licenses save ./cmd/trillian_log_signer --save_path /THIRD_PARTY_NOTICES
 ---> Running in 70dddf294b30
go: finding github.com/google/go-licenses latest
go: downloading github.com/google/go-licenses v0.0.0-20200227160636-0fa8c766a591
go: finding github.com/google/licenseclassifier v0.0.0-20190926221455-842c0d70d702
go: finding github.com/otiai10/copy v1.0.2
go: finding golang.org/x/sys v0.0.0-20191119060738-e882bf8e40c2
go: finding gopkg.in/src-d/go-git.v4 v4.13.1
go: finding github.com/otiai10/mint v1.3.0
go: finding github.com/otiai10/curr v0.0.0-20150429015615-9b4961190c95
go: finding github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
go: finding github.com/emirpasic/gods v1.12.0
go: finding github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
go: finding github.com/anmitsu/go-shlex v0.0.0-20161002113705-648efa622239
go: finding github.com/jessevdk/go-flags v1.4.0
go: finding golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
go: finding golang.org/x/tools v0.0.0-20190729092621-ff9f1409240a
go: finding github.com/gliderlabs/ssh v0.2.2
go: finding github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: finding gopkg.in/src-d/go-git-fixtures.v3 v3.5.0
go: finding gopkg.in/src-d/go-billy.v4 v4.3.2
go: finding github.com/xanzy/ssh-agent v0.2.1
go: finding github.com/pelletier/go-buffruneio v0.2.0
go: finding github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7
go: finding github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: finding github.com/stretchr/objx v0.2.0
go: finding golang.org/x/net v0.0.0-20190724013045-ca1201d0de80
go: finding github.com/src-d/gcfg v1.4.0
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding github.com/kr/pty v1.1.8
go: finding golang.org/x/sys v0.0.0-20190726091711-fc99dfbffb4e
go: gopkg.in/warnings.v0@v0.1.2: unknown revision v0.1.2
go: github.com/kr/pty@v1.1.8: unknown revision v1.1.8
go: error loading module requirements
ERROR: Service 'trillian-log-signer' failed to build: The command '/bin/sh -c go run github.com/google/go-licenses save ./cmd/trillian_log_signer --save_path /THIRD_PARTY_NOTICES' returned a non-zero code: 1

Could you please help me ?

**Comment by Martin2112** [comment]
It looks like a dependency issue. But I was just able to run the same command without seeing any errors so not sure exactly what the problem is.

**Comment by AlCutter** [comment]
I tried too - worked for me at commit `edb8c50ee82e5730a9c6fc32c064aa6736d55112`

**Comment by Keerthana-Jayakumaran** [comment]
Thanks. I am using "go version go1.13.8 linux/amd64". Could you please tell me which version you are using?

**Comment by pavelkalinnikov** [comment]
@Keerthana-Jayakumaran Sorry for the delayed response. Do you still need to resolve this? Feel free to reopen this issue, if yes.
