### ISSUE TITLE
Simplify log proofs generation

### ISSUE THREAD

**Issue by pavelkalinnikov** [google/trillian#2143]
The proofs generation code needs a refreshment. It is old, bulky, and has references to C++ implementation that is obsolete. For example, the [merkle/log_proofs.go](https://github.com/google/trillian/blob/bc537e07cd165bc877c05412174eba700f6981e6/merkle/log_proofs.go) file can be [reduced](https://github.com/google/trillian/pull/2142) by >200 LoC if it uses helpers from the compact ranges package.

Algorithmic components of Merkle trees are scattered across the codebase. For instance, it is clear that `Rehash` parameter is meant to be consumed by the [rehasher](https://github.com/google/trillian/blob/2123c407a3646b7544a218fa266b4cd87a2885f6/server/proof_fetcher.go#L52) type. This type should probably migrate to `merkle` folder and come in pair with `log_proofs.go`.

Plan:

- [x] Refactor tests (e.g. [merkle/log_proofs_test.go](https://github.com/google/trillian/blob/bc537e07cd165bc877c05412174eba700f6981e6/merkle/log_proofs_test.go)).
- [x] Increase coverage to >100% to prevent regressions.
- [x] Convert to using compact ranges in backwards-compatible way [[prototype PR](https://github.com/google/trillian/pull/2142)].
- [x] Move purely algorithmic components to `merkle`.

**Comment by pavelkalinnikov** [comment]
@AlCutter @Martin2112

**Comment by pavelkalinnikov** [comment]
The bigger goal is that `merkle` package is reuse-friendly.

**Comment by Martin2112** [comment]
Not sure what input you're looking for? It sounds like an improvement worth having. Al might have a view on whether to do it now or later.

**Comment by pavelkalinnikov** [comment]
This is just an FYI, to explain the bigger picture. I will be sending some PRs to you soon.
Re now/later, in my mind reusability of `merkle` package fits into the current goals as we'll be using it internally for some experiments.

**Comment by Martin2112** [comment]
OK if it helps current work that is an argument for doing it now.

**Comment by AlCutter** [comment]
👍  Sounds great!
