### ISSUE TITLE
How to fetch and verify  intermediate merkle tree hashes ?

### ISSUE THREAD

**Issue by ke389954** [google/trillian#2190]
Hi,
I have started using trillian. It's nice. Thank you.
In our application, we have to check whether the intermediate hashes are present. 
eg.
When I am hashing two leaves, I will get the hash1. The hash1 will be the root hash. when I am adding two nodes/ leaves one by one(i.e not at the same time). Now I will get the root hash as hash3. Then hash1 (root hash) becomes intermediate hash.
When I have gone through the consistency proof, I got to know that the tree is restructuring whole ( sometimes partially) every time when a node is/ nodes are adding.

From my understanding, I could get that " previous intermediate hashes(say hash1) will not retain / present in the future. since the hashing structure of the leaves keeps changing.
Is that correct?
If not, could you please guide me on how to check the intermediate hashes are present?

**Comment by pavelkalinnikov** [comment]
Hello. It would be helpful if you provided a description of a broader problem that you are trying to solve. Many problems can be solved by means of consistency and inclusion proofs rather than checking individual node hashes.

In the example that you provided, `hash1` of the first 2 leaves will always be present in a tree of size >= 2. More generally, for every node, its hash stays constant indefinitely, as soon as this node becomes a root of a perfect subtree (i.e. a subtree with 2^k leaves). For example, the node at (level 3, index 1), i.e. the node that covers leaves 8 through 15, will never change after the tree reaches size 16.

**Comment by ke389954** [comment]
Thanks, @pavelkalinnikov .  I understood. The hashes of the subtree structure will not change after it crossed 2^k leaves. 
**Application description:**
 I have to store sensor values for every 15 minutes and broadcast the root hash to the client. So, if I am getting the sensor value for every 15 minutes. tasks are storing, creating a root hash, and broadcast whenever the client is asking. 

Assume I got hash as RH12 when we hash the first two sensor values(S1 and S2). when I get the third sensor value(S3), it will produce a hash (say RH123) by hashing RH12 and S3 (3rd sensor value) and I am broadcasting RH123 to the client. 

when I get the fourth sensor value(S4), I will get the hashing structure as 

1.hash(hash(S3) || hash(S4)) => say RH34
2. now the hashes RH12 and RH34 will be hashed to produce a new hash. say RH.

From this, I could say that root hash RH3 will not be present in the subtree because S3 combined with S4.
From this context, the client is checking whether the "RH123" is present in the subtree or not. The answer will be false.
My question is: Is there any way that even when the tree root is RH,  I could verify that RH123 is present in the tree or a valid hash.
One way I could verify by hashing the consistency proof of RH (hashing appropriately to get RH123). But I have not tried. 
If I am wrong, Could you please guide me?

**Comment by pavelkalinnikov** [comment]
Hello again. In this example, do I understand correctly that your client needs to verify that the new tree state given to them (size 4, hash `RH`) is strictly an append-only modification of the previous state of this tree (size 3, hash `RH123`)?

It looks like you can use [GetConsistencyProof](https://github.com/google/trillian/blob/67e1f331149b29a182d55471f0343ca4674e6573/trillian_log_api.proto#L107) call to get this proof. You will then need to verify the consistency proof. You can use [LogVerifier](https://github.com/google/trillian/blob/67e1f331149b29a182d55471f0343ca4674e6573/client/log_verifier.go#L86) type, or [VerifyConsistencyProof](https://github.com/google/trillian/blob/67e1f331149b29a182d55471f0343ca4674e6573/merkle/log_verifier.go#L92) function for this purpose. What these functions do under the hood is essentially computing both `R123` and `RH` hashes, and making sure the second one is an extension of the first one.

**Comment by ke389954** [comment]
Thanks @pavelkalinnikov . I agree that this is an append-only structure and we can verify by getting the consistency proof. 
The part I m asking which sounds like inclusion proof but in another way. That is, if i am adding a leaf at some time t (may be an intermediate node) and getting a root(RH). After so many nodes been added (the tree structure been changed), Is it possible to verify that given roothash (RH) is valid for that tree. And also if i give some random roothash, i should able to prove that this root hash is not valid.

Because when the node is not a 2^k, then the tree structure will change. If the tree structure changes, it does not mean that the node values/leaves are not present/changed.  This one we can prove by consistency proof or inclusion proof. But the intermediate roothashes will be gone and will form the new intermediate root hashes according to the structure. Is that right?

**Comment by pavelkalinnikov** [comment]
Hello again. I think I understood your request, but please confirm. Your client gets an inclusion proof for an older tree, and wants to verify inclusion of this entry for newer versions of the tree.

An inclusion proof is valid only for the tree size that it was issued for. For example, if you get an inclusion proof for entry 10 in a tree of size 100, it is only applicable to tree of size 100. If you want to verify inclusion of entry 10 for a tree size 105 (for example), you have some options:

- Request a new inclusion proof for entry 10 at tree size 105.
- Use the old inclusion proof of entry 10 at tree size 100, but in addition request a consistency proof between tree size 100 and 105. Verifying these two proofs is equivalent to verifying inclusion of entry 10 in a tree of size 105.

**Comment by ke389954** [comment]
Thank you for your time @pavelkalinnikov.  So can I conclude that it is not possible to check directly whether the intermediate root hash is present in a tree or not? 
But we can achieve the same with the help of inclusion proof and consistency proof.

**Comment by pavelkalinnikov** [comment]
Yes, right now we don't have an API that would allow checking individual node hashes of the tree. Inclusion and consistency proofs are the most granular primitives that we have.

**Comment by ke389954** [comment]
Ok. Thank you @pavelkalinnikov

**Comment by ke389954** [comment]
Hi @pavelkalinnikov 
I am working on logic to fetch intermediate hashes. For that, I need to hash the proofs accordingly. I hope Trillian using the SHA256 hash technique. When I try to get hex code out of bytes, I am getting error as "invalid byte: U+00D1 'Ñ" .  If possible, could you please guide me on how to use the hashing technique on the proofs correctly?

**Comment by pavelkalinnikov** [comment]
Hello. Could you give more context?

1. Are you using Go or some other language?
2. Where did you get hashes/bytes from? Was it [`GetInclusionProof`](https://github.com/google/trillian/blob/db1696701784a745981d85938fe0b28c9dcc7990/trillian_log_api.proto#L83) or `GetConsistencyProof` RPC?
3. Why do you need to convert between bytes and hex?

If you use Go language, you can jus tuse one of the verifier functions I linked above.
