### ISSUE TITLE
Move tools.go to tools/tools.go

### ISSUE THREAD

**Issue by bartle-stripe** [google/trillian#2196]
https://github.com/google/trillian/blob/master/tools.go exists so that `go mod` can pull in dependencies that are used by out-of-band tools.  We're using trillian as a library and because we import go code under `github.com/google/trillian`, we end up pulling all the dependencies in `tools.go` (via `go mod vendor`), even though we don't necessarily use them.  If this file were moved to `tools/tools.go` we would no longer pull these in (because we wouldn't ever pull in `github.com/google/trillian/tools`).

**Comment by bartle-stripe** [comment]
I confirmed this does work by forking `trillian` with this file moved (https://github.com/bartle-stripe/trillian/commit/8b76dc06fe26843f34a3414ca54995bf8ca8885e), then added `replace github.com/google/trillian => github.com/bartle-stripe/trillian v0.0.0-20200716231446-8b76dc06fe26` to our `go.mod`, and verified a bunch of dependencies were dropped after running `go mod vendor`.

**Comment by Martin2112** [comment]
We questioned the usage of tools.go last week while trying to solve some dependency problems. @pphaneuf looked at it as well.

Does the proposed fix help people who aren't vendoring? Possibly tools could be a separate module but not sure if that's a good idea.

If we do move this we should probably check it's not referenced by examples or their deployments script.

**Comment by bartle-stripe** [comment]
Yes, with this change `go build` no longer downloads e.g. `github.com/fullstorydev/grpcurl` if you simply depend on `github.com/google/trillian`.

**Comment by bartle-stripe** [comment]
Creating a "sub" module under `github.com/google/trillian/tools` should work, though I'm not sure it'd be that useful -- typically you'd do that if you want to manage the "parent" and "sub" module versions independently (i.e. you might have a `v1.0.0` git tag for the parent module, but a `tools-v2.0.0` git tag for the sub module).

**Comment by Martin2112** [comment]
Yep not convinced by the module. 

@AlCutter this seems like a reasonable proposal to me, any thoughts?

**Comment by AlCutter** [comment]
Seems reasonable to me, and brings it into line with the golang [standard package layout](https://github.com/golang-standards/project-layout).
👍

**Comment by Martin2112** [comment]
OK I'll do a PR.
