### ISSUE TITLE
KV storage support

### ISSUE THREAD

**Issue by GrapeBaBa** [google/trillian#2213]
Guys, what's the consideration using SQL database instead of KV database(Rocksdb,Leveldb)? It seems KV database with better performance.

**Comment by GrapeBaBa** [comment]
Is this project still active?

**Comment by Martin2112** [comment]
Hi,

Yes it is.

Using something like leveldb is unlikely to provide sufficient availability as it's a single node. If you're working on some sort of embedded application where high availability isn't required then a nested KV store like boltdb can be made to work.

**Comment by GrapeBaBa** [comment]
Thanks @Martin2112
