### ISSUE TITLE
Are there any guidelines on how Trees should be defined ?

### ISSUE THREAD

**Issue by vin-fandemand** [google/trillian#2217]
Are there any guidelines on how Trees should be defined and the number of trees that could be defined?

**Comment by pavelkalinnikov** [comment]
Hello. Please elaborate your question, i.e. what you mean by defining a Tree.

If you want to **create** a tree, you need to:

1. Decide which [type](https://github.com/google/trillian/blob/fe57702b8d7948714ad469b44dde6859c01ba5a4/trillian.proto#L101) of tree you need, and its [parameters](https://github.com/google/trillian/blob/fe57702b8d7948714ad469b44dde6859c01ba5a4/trillian.proto#L124) like name etc. I'm guessing, you need a LOG?
1. Cast a [CreateTree](https://github.com/google/trillian/blob/fe57702b8d7948714ad469b44dde6859c01ba5a4/trillian_admin_api.proto#L99) RPC with the corresponding parameters. You can also use the [createtree](https://github.com/google/trillian/tree/master/cmd/createtree) tool.

We tested Trillian to serve 10-100 trees. It might scale to more trees, but probably not by orders of magnitude.
