### ISSUE TITLE
Tombstone and remove current map server & storage code

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#2284]
The newer approach is already present in the experimental directory, and early examples of how to use it is in the [experimental sumdb](https://github.com/google/trillian-examples/tree/master/experimental/batchmap/sumdb) project in trillian-examples.

**Comment by pavelkalinnikov** [comment]
KT depends on Maps as currently implemented. We would need to pin it to the latest release.

**Comment by pphaneuf** [comment]
Is KT in use? I think their repository is currently broken anyway?

**Comment by mhutchinson** [comment]
I propose that we create a Trillian release in the next week or so that still includes the map in its current state. The next release of Trillian will cut the map out. This seems like a reasonable compromise so that anyone still wanting to play with the old map can pin to this release, and it prevents the release being blocked on PRs which are deleting the map (which I imagine will take a while to see through).

**Comment by pphaneuf** [comment]
SGTM

**Comment by pavelkalinnikov** [comment]
Also, maybe we can time this with "finalising" v1 branch, and setting foundation for v2:

- Create a "permanent" v1 branch, with maps still in it. The last v1 release will be tagged on this v1 branch.
- Commit to v1 only to fix issues and support prod (including our internal).
- Start breaking things in master. Delete maps, minimise the rest of the code.
- Whenever ready, create v2 branch/label/release from master.

**Comment by pavelkalinnikov** [comment]
Deleting maps to some non-breaking degree could still be done in v1.

**Comment by pphaneuf** [comment]
I missed a detail previously: the KT repo (which I believe has been broken for other reasons for a good while) is pinning two Trillian versions behind.

So there's nothing we can do that will break KT any further, and this issue is essentially done?

**Comment by pavelkalinnikov** [comment]
Yeah, the KT aspect is no longer a factor/blocker here, I think.

The only remaining factor is that the last release was a few months ago, so we might want: a) fresh "final" map release, b) declaring in release notes that Map is being removed in the next release.

**Comment by pphaneuf** [comment]
If the "final" map-inclusive release is for the benefit of map users, my hypothesis is that there are none, and I would think that having it "one last time" can only encourage new potential users to appear (and soon be disappointed), even with an announcement?

**Comment by pphaneuf** [comment]
The backing for my hypothesis is that the map API as it is at the moment is so incredibly difficult to use "correctly" that I would consider it broken, and code using it likely to be broken as well (so removing it breaks nothing new).

**Comment by mhutchinson** [comment]
Marking this as fixed. Any remaining parts of the map should be fairly simple to remove as they are rediscovered. If that's not the case and I need to dive in further, then reopen this.
