### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by pavelkalinnikov** [google/trillian#2377]
- [ ] Tests using `testonly/flagsaver` package (e.g. `cmd/get_tree_public_key`) have data races on flags.
  - #2326 tried to fix this, but the problem appears again in the same test.
- [x] `TestSleepContext/20ms:10ms` flakes probably because of very short intervals:
  - `time_test.go:48: SleepContext() returned <nil>, want context deadline exceeded`
  - Hopefully a larger time gap will reduce the possibility of this effect: #2346.
- [ ] Race in [trillian/integration](https://storage.googleapis.com/trillian-cloudbuild-logs/log-2ac9093a-f2cd-4765-9e54-d79704ff7bef-step-6.txt).

**Comment by mhutchinson** [comment]
Have we seen this happening recently? I don't recall any instances of this flaking recently.

**Comment by pavelkalinnikov** [comment]
Yeah, I can't recollect recent failures of these.
