### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [google/trillian#2389]
[jw@cn06 trillian]$ sudo go build ./...
go: bitbucket.org/creachadair/shell@v0.0.6: Get "https://proxy.golang.org/bitbucket.org/creachadair/shell/@v/v0.0.6.mod": dial tcp: lookup proxy.golang.org: no such host
[jw@cn06 trillian]$

**Comment by pavelkalinnikov** [comment]
Looks like you have some issue with your local setup (could be Go, or network).

Could you try running this?
```shell
$ go version
$ go get bitbucket.org/creachadair/shell@v0.0.6
```

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 trillian]$ go version
go version go1.14.6 gccgo (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9) linux/arm64
[jw@cn06 trillian]$ go get bitbucket.org/creachadair/shell@v0.0.6
go: writing go.mod cache: mkdir /usr/local/go: permission denied
...
go: writing go.mod cache: mkdir /usr/local/go: permission denied
go: writing stat cache: mkdir /usr/local/go: permission denied
go: downloading bitbucket.org/creachadair/shell v0.0.6
go get: mkdir /usr/local/go: permission denied
[jw@cn06 trillian]$ sudo go get bitbucket.org/creachadair/shell@v0.0.6
go: bitbucket.org/creachadair/shell@v0.0.6: Get "https://proxy.golang.org/bitbucket.org/creachadair/shell/@v/v0.0.6.mod": dial tcp: lookup proxy.golang.org: no such host
[jw@cn06 trillian]$ nslookup proxy.golang.org
Server:         10.140.9.14
Address:        10.140.9.14#53

Non-authoritative answer:
Name:   proxy.golang.org
Address: 142.250.179.177
Name:   proxy.golang.org
Address: 2a00:1450:400e:802::2011

[jw@cn06 trillian]$

**Comment by pavelkalinnikov** [comment]
It looks like you have some issue on your machine that prevents building Go programs in general.

One thing, you probably set up the Go environment incorrectly, since you need `sudo` to run the build. The directory structure should look like this: https://golang.org/cmd/go/#hdr-Internal_Directories. Try setting it up from scratch as follows:

```
$ cd ~
$ mkdir go && cd go
$ go get github.com/google/trillian
```

If "no such host" error persists, see what `go env GOPROXY` says, and consider [setting](https://golang.org/ref/mod#environment-variables) `export GOPROXY=direct` and try again.

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 jw]$ mkdir go && cd go
[jw@cn06 go]$ go get github.com/google/trillian
package github.com/google/trillian: mkdir /usr/local/go: permission denied
[jw@cn06 go]$ sudo go get github.com/google/trillian
# cd .; git clone -- https://github.com/google/trillian /root/go/src/github.com/google/trillian
Cloning into '/root/go/src/github.com/google/trillian'...
fatal: unable to access 'https://github.com/google/trillian/': Could not resolve host: github.com
package github.com/google/trillian: exit status 128
[jw@cn06 go]$ go env GOPROXY
https://proxy.golang.org,direct
[jw@cn06 go]$ export GOPROXY=direct
[jw@cn06 go]$ sudo go get github.com/google/trillian
# cd .; git clone -- https://github.com/google/trillian /root/go/src/github.com/google/trillian
Cloning into '/root/go/src/github.com/google/trillian'...
fatal: unable to access 'https://github.com/google/trillian/': Could not resolve host: github.com
package github.com/google/trillian: exit status 128
[jw@cn06 go]$

**Comment by pavelkalinnikov** [comment]
I think you have some DNS issue, as the commands could not resolve "github.com" and "proxy.golang.org". Also, you shouldn't need sudo/root to build Go programs; try your best to avoid it. Try setting `GOPATH` to the go directory that you created in your home folder: `export GOPATH=$HOME/go`, and try "go get" again.

If that doesn't work, I'm afraid I can't help you, as this is clearly an issue with your local environment/Go. Try reaching out to Go team (e.g. this [issue](https://github.com/golang/go/issues/27187) seems similar).

**Comment by LutzWeischerFujitsu** [comment]
Tried fresh and it works now.
