### ISSUE TITLE
Consistency proofs between zero tree sizes + a non zero size

### ISSUE THREAD

**Issue by Martin2112** [google/trillian#245]
Currently the log backend rejects them. Should probably do the same thing as current log implementations, which I think is returning an empty proof but no error.

**Comment by Martin2112** [comment]
I think we can close this as the CT personality has to handle this case and we have integration tests. Not sure we're testing this case though? @daviddrysdale probably knows.

**Comment by daviddrysdale** [comment]
We're not yet testing this case, and it fails with the current code (`error: failed to parse consistency range: first and second params cannot be <=0`) so best to leave open for now.

The existing logs just return an empty proof for `first=0`, so it should be easy to behave similarly.
