### ISSUE TITLE
remove signing and signatures

### ISSUE THREAD

**Issue by pphaneuf** [google/trillian#2450]
Early on, we had hope that Trillian could be run in a separate trust domain, and that Trillian data structure might become commonly exchanged in distributed systems. In practice, there seems to be too much variation in the needs of different ecosystems. In addition to that, Trillian is not currently suitable to be run in its own trust domain, and providing signatures can provide a false sense of security. They also bring a lot of complexity, in the form of key management.

**Comment by AlCutter** [comment]
Is there more to do on the signatures or can we close this?

**Comment by pphaneuf** [comment]
There is a bit more, I was just letting the previous changes settle in, but I'll get back on it soon to finish it up.

**Comment by garantir-km** [comment]
I am not fully following the reasoning for removing signatures. I see the reasons listed as:

1. They provide a false sense of security
2. Key management is difficult

Number 1 can be resolved with documentation on how to **fully** verify a log entry. In particular, verifying a signature should be a necessary but not sufficient condition to verifying the log entry. As for number 2, Trillian doesn't need to solve the key management issue. It can just support a standard crypto interface (e.g., PKCS11) as well as software-based keys (e.g., PKCS12) for those looking for easier deployments. How those keys are managed is up to the end users. At the very least, they are no worse off (security-wise) for using signatures as compared to not using signatures.

**Comment by pphaneuf** [comment]
The "false sense of security" is not related to the verification of a given log entry, but rather, to the effective isolation of different users of a shared Trillian instance. In effect, this demonstrates my argument, as signatures would be required for such a deployment, but would be in no way sufficient, and their presence seem to make people think that the other aspects would also be covered.

These other aspects are not covered, and we have no intention of covering them (they are not a "work in progress"), so this is actively misleading.

The key management *code* in Trillian is not that complex (there was in fact PKCS11 support), but it complicates deployment beyond what is reasonable, especially in consideration of the signatures not actually permitting the benefit that they might.

The only reasonable deployment environment for Trillian at this time and for the expected future is where the Trillian RPC client (such as CTFE, for example) is in the same trust domain.
