### ISSUE TITLE
QueueLeaves should not be part of the LogTX

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#255]
When adding a batch of leaves some leaves could fail, e.g. due to dupe keys, and the log shouldn't ditch the rest of the batch due to an unrelated dupe entry. Rather, it should submit as many as it can, and report those which failed to the caller.

**Comment by Martin2112** [comment]
Wasn't this fixed by changes David made?

**Comment by Martin2112** [comment]
Dup of #256. Leaving that one open as it does not mandate changing tx semantics.
