### ISSUE TITLE
QueueLeaves should return individual status for each leaf

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#256]
Currently, the storage.QueueLeaves API effectively enforces an all-or-nothing failure mode for the addition of each leaf in the array, which is not ideal. E.g. this would cause a batch of additions to fail if the log didn't accept dupes but one was presented.

**Comment by Martin2112** [comment]
I think this might have been implemented in the last round of API changes but need to confirm.

**Comment by daviddrysdale** [comment]
Yep, the API now has the ability to return per-leaf status (in a `QueuedLogLeaf` message)
