### ISSUE TITLE
Update the dependency on google.golang.org/grpc?

### ISSUE THREAD

**Issue by eclipseo** [google/trillian#2612]
Would it be possible to update the dependency on google.golang.org/grpc to the latest release?
Thanks.

**Comment by AlCutter** [comment]
Hi @eclipseo , thanks for the request!

I think we're already on the latest v1.40.0 of grpc thanks to dependabot (https://github.com/google/trillian/commit/07451279ffc915c4b64e06a7919e516fb184236d), but I don't think we've cut a Trillian release containing that commit yet... Let me see if we can make a release soon!

Cheers,
Al.

**Comment by AlCutter** [comment]
Here you go: https://github.com/google/trillian/releases/tag/v1.4.0
Enjoy!
