### ISSUE TITLE
Tag a new release with transparency-dev/merkle extracted

### ISSUE THREAD

**Issue by aarongable** [google/trillian#2727]
Much of the underlying merkle functionality has been extracted into the standalone https://pkg.go.dev/github.com/transparency-dev/merkle package, which is great.

However, the currently-released version of Trillian (v1.4.0) still has a public interface which returns pre-extraction versions of these merkle types. For example: https://pkg.go.dev/github.com/google/trillian@v1.4.0/storage/tree#Node (which is returned by functions such as https://pkg.go.dev/github.com/google/trillian/storage#MockLogTreeTX.GetMerkleNodes) still embeds a `google/trillian/merkle/compact.NodeID`.

Please tag a new release of this repository which uses the extracted types so that downstream projects can also update to use the transparency-dev/merkle package.

**Comment by pavelkalinnikov** [comment]
Preparing `v1.4.1` release.

**Comment by pavelkalinnikov** [comment]
Both Merkle and Trillian are now released:
- https://github.com/transparency-dev/merkle/releases/tag/v0.0.1
- https://github.com/google/trillian/releases/tag/v1.4.1

We will also release `github.com/google/certificate-transparency-go` shortly.

**Comment by pavelkalinnikov** [comment]
@aarongable Let me know if you need help / review in updating the code on your end.

**Comment by aarongable** [comment]
Perfect thanks! I have a PR for ct-woodpecker that updates trillian to this new release, and replaces all uses of its `merkle` package with transparency-dev/merkle instead.
