### ISSUE TITLE
Need API for creating new logIDs

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#310]
We need some kind of administrative API that supports creating and deleting LogIDs. 
There's ongoing work on an admin API. Not sure how to connect this bug to that.

**Comment by codingllama** [comment]
Yep, that's on my plate. Thanks for raising the issue. Expect PRs to start appearing soon.

**Comment by gdbelvin** [comment]
Partal work in #319

**Comment by codingllama** [comment]
Quick update:

The Admin API is now available and largely implemented (Create and Get methods). New trees may be provisioned either via RPCs or using the `cmd/createtree` command. REST support has also been added (barring google.protobuf.Any woes).

More work still needs to be done (implement remaining RPCs, wire a few things internally), but there's enough functionality now to unblock most clients.

**Comment by Martin2112** [comment]
Assigning to M8 provisionally. Feel free to move it if you think this is wrong.

**Comment by codingllama** [comment]
The Admin API is in good shape, so I officially declare this closed.

We still don't support DeleteTree (nor undelete). I've raised #590 to track it, but I'll push it to a separate milestone.
