### ISSUE TITLE
Hashing Interface

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#331]
Hasher needs to be an interface to support alternative hashing implementations. 
Here's a proposal that supports both logs and maps.  
Individual implementations are not required to incorporate all input fields into their hash. 

```
// TreeHasher provides hash functions for tree implementations.
type TreeHasher interface {
	HashLeaf(treeID, index []byte, depth int, dataHash []byte) Hash
	HashEmpty(treeID, index []byte, depth int) Hash
	HashInterior(left, right Hash) Hash
}
```

Steps:
- [x] Move HashKey to Personality
- [x] Create Hasher interface
- [x] Create test implementations
- [x] Migrate to new function interfaces.

**Comment by codingllama** [comment]
I'd suggest renaming HashInterior() to HashNode().

Do we expect leaves to have depth = 0? Because, if so, that's height, not depth (https://stackoverflow.com/questions/2603692/what-is-the-difference-between-tree-depth-and-height)

**Comment by Martin2112** [comment]
I'm not clear if this will turn out to be a special case for Key Transparency. If so then every other client will have stuff in the API that they don't use. Is there maybe a better way?

@codingllama  We've used 'depth' a lot in the code as well as 'level', which is what we probably should have stuck to.

**Comment by codingllama** [comment]
Isn't the depth/height/level, in a way, a component of the index? I don't see too much problem in including it there.

Some smalls inconsistencies do bother me, though:
* "dataHash []byte" vs "left, right Hash" - Why not make all of them Hash?
* HashInterior has neither index nor depth - That makes the interface KT specific, IMO
* treeID should probably be an int64

We may also want a type to represent the (index, depth) pair.

@Martin2112 If we mean "height" when we say "depth", we should at least stop using the latter.

**Comment by Martin2112** [comment]
It's effectively part of the NodeID in logs but not maps and is not part of the hash in logs or our existing maps. We should try to keep anything outside of personality code as generic as possible. I'm just questioning if we've done that here. It may not be possible to do it cleanly either.

Depth probably crept in from the RFC where trees grow from the top down. For obvious reasons we don't want to have to update as the tree grows so we work in the other direction. All I'm saying is that there may well be places where it's been used instead of node level, which could cause confusion. In some places e.g. the strata code depth is the correct term. I don't know whether Gary is using it in the correct sense here.

**Comment by gdbelvin** [comment]
Incorporating the comments above:

```
// TreeHasher provides hash functions for tree implementations.
type TreeHasher interface {
	HashLeaf(treeID int64, index []byte, depth int, dataHash Hash) Hash
	HashEmpty(treeID int64, index []byte, depth int) Hash
	HashInterior(left, right Hash) Hash
}
```

I'm using depth to indicate the number of bits to use from the index, with the MSB on the left, starting at 0 for the root. Eg. The root hash of an empty tree would be `HashEmpty(treeID, []byte{}, 0)`

**Comment by Martin2112** [comment]
Isn't that sort of duplicating what's in a NodeID? It's also kind of hiding the different way these are used for logs but that may not entirely matter as we won't be hashing depth in logs anyway.

I need to take a break from this now, it's been a very busy day.

**Comment by gdbelvin** [comment]
There's some duplication...
- Should the merkle library depend on the storage layer?
- NodeID also contains a prefix offset, which I don't understand. 
- Should NodeID also contain a treeID?

**Comment by Martin2112** [comment]
I don't think we should mix up node ids and tree ids. I'm not sure but I think NodeID is a different abstraction from what we're considering here. You could make a better argument that the original design was CT specific but currently I don't know of anything except KT that uses levels in hashes.

I think we can probably solve this more easily round a whiteboard than on a long email thread.

**Comment by Martin2112** [comment]
@gdbelvin did this get completed as part of the client? Can you comment and update assignment if necessary.
