### ISSUE TITLE
Entries getting added to TreeHead table even if Rekor APIs are not invoked

### ISSUE THREAD

**Issue by subhamoycomputer** [google/trillian#3548]
Hi All,

once we bring up Rekor in our local system, we have seen one unusual behavior. Even though the APIs are not in use, still there are entries getting added to the “TreeHead” table constantly at random periodic intervals. It is hecause of this behavior the data count in TreeHead table is constantly increasing.
Is this a known behaviour? Can this be stopped by setting any flags on startup commands ?

**Comment by roger2hk** [comment]
Did you set the `max_root_duration` when the tree was created? The default is one hour.

https://github.com/google/trillian/blob/6a1e99f2fffe50e0eea980688ca14edeedaf6b9d/cmd/createtree/main.go#L53

If you follow the [SigStore installation steps](https://docs.sigstore.dev/logging/installation/#build-trillian), it does not set the `max_root_duration` in the `create_tree` command.

**Comment by subhamoycomputer** [comment]
Thanks for your prompt response.

we did try to bring up createtree with the max_root_duration=0 but still entries are getting added to the TreeHead table.

**Comment by mhutchinson** [comment]
@subhamoycomputer are new leaves being added (i.e. the tree size is changing), or are you only seeing new tree heads for the same size of tree?

@roger2hk replied assuming that the tree size is not growing. The [code that creates new tree heads](https://github.com/google/trillian/blob/ed2fb308c3c12273fdb13dae9c54e3b413c2d0e2/log/sequencer.go#L332) explicitly checks whether there is work to perform and exits if there are no leaves and the max root interval is 0.

Diagnostics that would be helpful:

- 2 consecutive tree heads
- Logs from your sequencer jobs
  - can be filtered to that `sequencer.go` method linked above
  - Even better if you can turn the verbosity of these tasks to 1 so we can see everything going on in that block

**Comment by subhamoycomputer** [comment]
Thanks for your response.

So this is the first time we installed with no active incoming traffic. I saw in the TreeHead table, new rows are getting added for the same TreeID and TreeSize is 0, only TreeRevision is getting increased by 1 for every new row that is added.

**Comment by roger2hk** [comment]
@subhamoycomputer I couldn't replicate the issue with the following steps. There is only one row in the `TreeHead` table after around 20 hours. Please provide the steps to replicate this issue for further troubleshooting.

---

**Bring up a Trillian log instance (server, signer and mysql database)**

```
git clone https://github.com/google/trillian.git
cd trillian
docker compose -f examples/deployment/docker-compose.yml up
```

**Create a new tree with zero `max_root_duration`**

```
➜  trillian git:(master) go run github.com/google/trillian/cmd/createtree@master --admin_server=localhost:8090 --max_root_duration=0s
go: downloading github.com/google/trillian v1.6.1-0.20240704103306-7f1ce4ce467c
go: downloading k8s.io/klog/v2 v2.130.1
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240624140628-dc46fd24d27d
go: downloading google.golang.org/genproto v0.0.0-20240624140628-dc46fd24d27d
go: downloading golang.org/x/sys v0.21.0
go: downloading golang.org/x/net v0.26.0
I0705 20:51:27.982173   80618 main.go:110] Creating tree tree_state:ACTIVE  tree_type:LOG  max_root_duration:{}
W0705 20:51:27.982371   80618 rpcflags.go:36] Using an insecure gRPC connection to Trillian
I0705 20:51:27.982714   80618 admin.go:50] CreateTree...
I0705 20:51:27.998957   80618 admin.go:95] Initialising Log 5356290855656069834...
I0705 20:51:28.026024   80618 admin.go:106] Initialised Log (5356290855656069834) with new SignedTreeHead:
log_root:"\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00 \xe3\xb0\xc4B\x98\xfc\x1c\x14\x9a\xfb\xf4șo\xb9$'\xaeA\xe4d\x9b\x93L\xa4\x95\x99\x1bxR\xb8U\x17\xdflS_\x86uG\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
5356290855656069834
```

**Read the `TreeHead` table**

```
➜  trillian git:(master) docker exec -it deployment-mysql-1 mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 13
Server version: 8.4.1 MySQL Community Server - GPL

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select * from TreeHead;
+---------------------+---------------------+----------+--------------------------------------------------------------------+------------------------------+--------------+
| TreeId              | TreeHeadTimestamp   | TreeSize | RootHash                                                           | RootSignature                | TreeRevision |
+---------------------+---------------------+----------+--------------------------------------------------------------------+------------------------------+--------------+
| 5356290855656069834 | 1720212688019551559 |        0 | 0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855 | 0x                           |            0 |
+---------------------+---------------------+----------+--------------------------------------------------------------------+------------------------------+--------------+
1 row in set (0.00 sec)
```

**Comment by subhamoycomputer** [comment]
The commands which we have used are as follows:

1. setsid ./trillian_log_server —logtostderr —mysql_uri=un/pwd
2. setsid ./trillian_log_signer —logtostderr —force_master —rpc_endpoint=localhost:8190 —http_endpoint=localhost:8191 —batch_size=1000 —sequencer_guard_window=0 —sequencer_interval=200ms —mysql_uri=un/pwd
3. setsid ./createtree —admin_server=localhost:8090
4. setsid ./rekor-server —scheme=“https” —rekor_server.address=some valid values —enable_retrieve_api=false —enable_api_endpoints=“createLogEntry,getLogEntryByUUID” —tla-port=3001 host=some valid values

the above packages were downloaded from respective git repo mentioned in the Rekor installation document.

**Comment by roger2hk** [comment]
> The commands which we have used are as follows:
> 
> 1. setsid ./trillian_log_server —logtostderr —mysql_uri=un/pwd
> 2. setsid ./trillian_log_signer —logtostderr —force_master —rpc_endpoint=localhost:8190 —http_endpoint=localhost:8191 —batch_size=1000 —sequencer_guard_window=0 —sequencer_interval=200ms —mysql_uri=un/pwd
> 3. setsid ./createtree —admin_server=localhost:8090 —max_log_duration=0s
> 4. setsid ./rekor-server —scheme=“https” —rekor_server.address=some valid values —enable_retrieve_api=false —enable_api_endpoints=“createLogEntry,getLogEntryByUUID” —tla-port=3001 host=some valid values
> 
> the above packages were downloaded from respective git repo mentioned in the Rekor installation document.

Please provide the result of the following queries. If there is no hint, we may need to add an INSERT trigger to collect the `TreeHead` table to figure out the unexpected pattern.

```sql
select TreeId, TreeState, TreeType, CreateTimeMillis, UpdateTimeMillis, MaxRootDurationMillis from Trees;
select * from TreeHead;
```

**Comment by subhamoycomputer** [comment]
Hey Hi, for the last couple of weeks we tried doing some testing. We created a fresh new schema and started createtree with max_root_duration = 0s. We didnt find any entries getting added in the TreeHead table.
Even after adding a couple of entries through the API, we didnt find any random entries getting added to the table. 

Thanks a ton for your help. One question - what is the need to add new TreeHead when max_root_duration is not set to zero ? What is the importance of doing this ? If you could explain it would be helpful.

**Comment by mhutchinson** [comment]
The motivation behind this feature is for situations like CT that require a fresh STH timestamp even if no new data has been added. From https://www.rfc-editor.org/rfc/rfc6962.html#section-3.5:

```
   Each log MUST produce on demand a Signed Tree Head that is no older
   than the Maximum Merge Delay.  In the unlikely event that it receives
   no new submissions during an MMD period, the log SHALL sign the same
   Merkle Tree Hash with a fresh timestamp.
```

I'll mark this issue as closed. If you're looking to be part of the transparency community, feel free to join us over on Slack: https://join.slack.com/t/transparency-dev/shared_invite/zt-27pkqo21d-okUFhur7YZ0rFoJVIOPznQ
