### ISSUE TITLE
Does createtree command needs to be executed during every restart of Trillian services ?

### ISSUE THREAD

**Issue by subhamoycomputer** [google/trillian#3585]
Is the “createtree” command need to be executed every time we start Rekor services ?
We setup Rekor for the first time in our server and ran the commands for Trillian log server, Trillian log signer, Createtree and Rekor server. Question is - whenever we restart our servers do we need to run createtree command every time or is it required only for the first time run ?

**Comment by roger2hk** [comment]
It is only required when you setup the Trillian for the first time. You will use the same tree after server restart.

https://docs.sigstore.dev/logging/installation/#build-trillian
