### ISSUE TITLE
KeyManager: Perform all key verification during New* functions

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#381]
The KeyManager interface currently supports returning `error` for several of the Get* functions. 
This dramatically increases code complexity for calling functions.  All these error params can be eliminated if the New* functions require a valid key to be loaded before returning a KeyManager object. Is there a strong reason to support starting Trillian without key material? 

```
type KeyManager interface {
	Signer() (crypto.Signer, error)
	SignatureAlgorithm() spb.DigitallySigned_SignatureAlgorithm
	HashAlgorithm() crypto.Hash
	GetPublicKey() (crypto.PublicKey, error)
	GetRawPublicKey() ([]byte, error)
}
```

Proposed interface:
```
New(...) (KeyManager, error)
type KeyManager interface {
	Signer() crypto.Signer
	SignatureAlgorithm() spb.DigitallySigned_SignatureAlgorithm
	HashAlgorithm() crypto.Hash
	GetPublicKey() crypto.PublicKey
	GetRawPublicKey() []byte
}
```

**Comment by Martin2112** [comment]
Probably OK as long as you can guarantee it won't break with more realistic implementations. 

Also it's potentially losing the detailed information in the error as to why the key was invalid if done via New() .

**Comment by gdbelvin** [comment]
I don't think it will break realistic implementations. 
I expect that key material should be available on server start and errors should be caught fairly early. Also, if we need to distinguish between multiple error cases in `New` we can define specific errors.

**Comment by Martin2112** [comment]
Not sure. Constructors really shouldn't be doing significant work (like reading files) and having constructors that can fail is usually an anti-pattern.

What might work is separating out all the code that decodes keys and having the PEM key manager constructor just take the keys. I don't know if this is better without trying it.

**Comment by gdbelvin** [comment]
I know that in other languages, constructors should not return errors, but
I'm not sure this applies to go.
For example, take a look at the os.Open() API which returns a (*File, error)
https://blog.golang.org/error-handling-and-go

One could think of this as a constructor / factory since it returns a File
object.

**Comment by pphaneuf** [comment]
FYI, the one example of a constructor in Effective Go is one that can fail:

https://golang.org/doc/effective_go.html#composite_literals

The pattern of "constructors shouldn't be doing significant work" is mostly for languages like C++, where they can get invoked implicitly, but just about nothing is implicit in Go, so no problem, significant work and failure are totally fine, especially if it can reduce the state space of the returned object!

**Comment by Martin2112** [comment]
I sometimes think Go was designed purely to contradict every other existing language.
