### ISSUE TITLE
Integration tests on Travis are flaky

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#382]
They sometimes fail with the server complaining that a port is already in use.

**Comment by RJPercival** [comment]
Example error message (from https://travis-ci.org/google/trillian/jobs/195912974): 
`E0127 15:51:22.605236   10557 main.go:142] Failed to listen on the server port: 36962, because: listen tcp :36962: bind: address already in use`

**Comment by daviddrysdale** [comment]
Hopefully fixed with pull #383
