### ISSUE TITLE
Occasional test failures due to database locking problems

### ISSUE THREAD

**Issue by daviddrysdale** [google/trillian#405]
Examples:

```
log_integration_test.go:97: Test failed: failed to queue leaves: rpc error: code = 2 desc = Unsequenced: Error 1213: Deadlock found when trying to get lock; try restarting 
```

**Comment by daviddrysdale** [comment]
Thoughts so far:

 - We could/should consistently order writes to `Unsequenced`; see pull #408 
 - Maybe convert `QueueLeaves` so it doesn't do multiple leaves in one big transaction; this also allows a per-leaf return code.
 - Somewhere along the chain (client -> CT front end -> log RPC server -> storage layer) needs to cope with a retryable failure and retry; probably more than one place in fact.

**Comment by Martin2112** [comment]
Is this still happening on Travis? I'm not seeing locking issues in large load tests but I have got a slightly different version of the code.

**Comment by codingllama** [comment]
I haven't seen this in a while. I'm OK with closing/marking as obsolete.

**Comment by Martin2112** [comment]
OK. I think Davids changes might have fixed it. We can reopen if necessary.
