### ISSUE TITLE
Resend original SCT if a client submits a certificate that already exists in the log

### ISSUE THREAD

**Issue by jcao219** [google/trillian#415]
Currently, if a client sends the same certificate twice, on the second time, it will fail with `AddChain handler error: backend QueueLeaves request failed: rpc error: code = AlreadyExists desc = Leaf hash already exists` due to https://github.com/google/trillian/blob/master/examples/ct/handlers.go#L308.

To comply with the RFC, any valid submission must yield an SCT.

**Comment by daviddrysdale** [comment]
Fixed by #421
