### ISSUE TITLE
Fix MySQL storage statement leak

### ISSUE THREAD

**Issue by Martin2112** [google/trillian#416]
Might possibly be only in my branch but needs investigating. Occurred after about 14.5M leaves sequenced. It's a server global setting so could be in any code that interacts with prepared statements.

```
W0307 08:33:03.287471    7153 sequencer.go:170] 0: Sequencer failed to start tx: failed to get tree row for treeID 
0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
W0307 08:33:03.287493    7153 sequencer_manager.go:110] 0: Error trying to sequence batch for: failed to get tree r
ow for treeID 0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
W0307 08:33:03.389171    7153 sequencer.go:170] 0: Sequencer failed to start tx: failed to get tree row for treeID 
0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
W0307 08:33:03.389193    7153 sequencer_manager.go:110] 0: Error trying to sequence batch for: failed to get tree r
ow for treeID 0: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
```

**Comment by Martin2112** [comment]
FYI @daviddrysdale in case you've seen this in your test runs.

**Comment by Martin2112** [comment]
There were just over 50K tree heads written so it's not losing one statement per sequencing run.

**Comment by codingllama** [comment]
I've seen a similar error ("too many connections") due a missing tx.Rollback() at [#328](https://github.com/google/trillian/pull/328/files#diff-ab28bb7ffee2dfa72ae70ed097aeec86R137). Avoiding that was the intent of #397 as well.

I haven't double checked statements, though. I wish we had some sort of code analysis for that.

**Comment by Martin2112** [comment]
I notice that the registry creates a new log storage each time, which don't share a statement cache (in tree storage). There is no close mechanism for tree storage so nothing appears to be freeing the cached statements.

**Comment by codingllama** [comment]
@RJPercival has been putting together some registry changes, which will likely sort that out too. Meanwhile, you could try to change LogStorage a shared instance and see if that fixes it?

**Comment by Martin2112** [comment]
I think that will fix it. I'm working on an experimental branch so it won't affect anybody else.

**Comment by Martin2112** [comment]
That does seem to be the cause.

```
+---------------------+--------+
| Variable_name       | Value  |
+---------------------+--------+
| Com_prepare_sql     | 0      |
| Com_stmt_prepare    | 311061 |
| Com_stmt_reprepare  | 0      |
| Com_xa_prepare      | 0      |
| Handler_prepare     | 896280 |
| Prepared_stmt_count | 6      |
+---------------------+--------+
```
