### ISSUE TITLE
Follow Go context best practices

### ISSUE THREAD

**Issue by codingllama** [google/trillian#419]
Per style guide, Go contexts should be passed in as the 1st parameter of functions, not be made into struct members.

https://github.com/golang/go/wiki/CodeReviewComments#contexts

**Comment by daviddrysdale** [comment]
Also, it would be good to use `context` throughout (i.e. remove pre-Go 1.7 imports of `golang.org/x/net/context`)

**Comment by gdbelvin** [comment]
FYI, grpc uses the pre 1.7 `golang.org/x/net/context`: https://github.com/grpc/grpc-go/issues/711.
Until grpc updates, we might find it difficult to switch ourselves.  +1 to both ideas though.

**Comment by Martin2112** [comment]
It looks to me that we can't get rid of the old context yet.

Assuming we've cleaned up the code that holds on to contexts? I propose we close this and reopen when we can address the other issue.

**Comment by codingllama** [comment]
Moving out of net/context is not the only work item here. I'd like to make sure we're passing contexts appropriately down the layers and not taking ctx objects as struct attributes. (Plus, it may be that we can minimize net/context usage; I'm not entirely sure.)

**Comment by Martin2112** [comment]
Sounds like there is still work to be done. I'll pick a milestone to start the ball rolling.

**Comment by codingllama** [comment]
I think I'm happy enough to close this now and deal with any stragglers separately. Any objections?

**Comment by Martin2112** [comment]
Not from me. Thanks for doing the changes.
