### ISSUE TITLE
GoMock expectations commonly use AnyTimes(), which includes 0 times

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#422]
Most of our gomock function call expectations use `AnyTimes()`. This means tests will pass even if those functions are never called. This appears to not be the intention in some of our tests. Consider replacing `AnyTimes()` with `MinTimes(1)` where appropriate.

**Comment by Martin2112** [comment]
I currently don't think we have time to go through all these. It would be a nice to have though. Shall we close it for now?
