### ISSUE TITLE
Serve APIs over TLS?

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#428]
`server/trillian_log_server` does not currently support TLS.  
This could be intentional because Trillian is designed to be a backend service. 
If it ever becomes publicly accessible, we should support gRPC over TLS and authentication.

**Comment by Martin2112** [comment]
We should probably support TLS but it wasn't a priority in early development.

**Comment by Martin2112** [comment]
Related to #477.

**Comment by Martin2112** [comment]
I think this was implemented. Reopen if I'm wrong.
