### ISSUE TITLE
Return correct GRPC codes

### ISSUE THREAD

**Issue by codingllama** [google/trillian#432]
GRPC codes help callers distinguish errors without the nastiness (and inherent flakiness) of parsing error strings.

Due to most of our errors being "regular" errors, GRPC assigns `codes.Unknown` to most of them. The specifics of how we solve this problem is still TBD with the team.

https://godoc.org/google.golang.org/grpc/codes

**Comment by Martin2112** [comment]
I think we decided how to proceed on this?

**Comment by codingllama** [comment]
Yes, the associated PRs have more extensive documentation.

I've kept the issue open as we've done little work on existing servers (log and map) to ensure they return appropriate codes. The upside is that new code is correct.

TL;DR: We have a TrillianError class and related utilities (Errorf, New) that allow us to map errors to gRPC codes, while keeping packages not related to gRPC independent of it. There's a translation layer at the server level that turns TrillianErrors into gRPC errors.

**Comment by Martin2112** [comment]
Right, makes sense to leave it open then.

Martin

**Comment by Martin2112** [comment]
I'm closing this as I think we've done the initial work needed for CT. Reopen if you disagree.
