### ISSUE TITLE
Example CT server only binds to localhost

### ISSUE THREAD

**Issue by lidavidm** [google/trillian#452]
The example CT server explicitly binds to only localhost. It would be nice to have this be configurable in case we want to expose the CT server (e.g. for Docker or something similar).

I can work on this (since it's a minimal patch), unless it's not something that we want to have (if the example is really meant only as an example).

**Comment by daviddrysdale** [comment]
Good point, that needs fixing -- feel free to have a go (and thanks).  The `examples/ct` code is going to become a full CT personality, so this will definitely be useful.
