### ISSUE TITLE
add metrics and support for monitoring them

### ISSUE THREAD

**Issue by pphaneuf** [google/trillian#467]
Monitoring is obviously an important aspect of running a production service. We will be needing to provide visibility into various inner workings, to be able to alert on and debug issues. These metrics are also useful during development, and while trying to evaluate the performance of the system.

The general plan is to have metric objects that can be exported in various ways, notably to something like Prometheus. But initially it will be simpler, mainly focused on facilitating development.

**Comment by rolandshoemaker** [comment]
Given that Google deployments will most likely use some magic internal monitoring system is the current plan to implement a basic pluggable interface for metrics or would it be plausible to do native Prometheus stats and do the translation between metrics types behind the scenes/outside of trillian?

I think either way is fine but the former is likely to become a bit complicated in terms of coming up with an interface that satisfies the various styles of metrics different systems use.

**Comment by pphaneuf** [comment]
We're currently leaning towards using the Prometheus Go library, and do something behind the scene for our internal monitoring. We might have to require something like having the `Registry` passed in, say, but it shouldn't be too obtrusive?

**Comment by rolandshoemaker** [comment]
:+1:, sounds good to me.

**Comment by Martin2112** [comment]
I think this is done now?
