### ISSUE TITLE
Documentation for log deployment and basic operational tasks

### ISSUE THREAD

**Issue by Martin2112** [google/trillian#491]
Need something similar to what we have for CT on how to set up and run a log in a clustered environment.

**Comment by RJPercival** [comment]
For reference, this is what we have for CT (using the deprecated C++ logs): https://github.com/google/certificate-transparency/blob/master/docs/Deployment.md

**Comment by AlCutter** [comment]
There are docs on setting up a clustered CT/Trillian deployment in the CT repo: 
https://github.com/google/certificate-transparency-go/tree/master/trillian#deployment

**Comment by pavelkalinnikov** [comment]
There is also info in this repo: https://github.com/google/trillian/tree/master/examples/deployment

**Comment by pavelkalinnikov** [comment]
And here: https://github.com/google/trillian/tree/master/deployment

What's the different between "deployment" and "examples/deployment" paths, by the way?

**Comment by pavelkalinnikov** [comment]
The "examples/deployment" is less supported.
