### ISSUE TITLE
Document intended usage of the errors package

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#508]
The `errors` package could use some extra documentation to indicate how it should be used. In particular, it should state that the error codes should describe the problem from the perspective of an RPC client, rather than from the perspective of the function itself.

For example, in [this code review](https://github.com/google/trillian/pull/480#discussion_r108390398), a function (`NewFromPrivatePEMFile`) could not find the specified file and so returned an error with code `errors.NotFound`. However, review feedback indicated that it should return `errors.FailedPrecondition` instead, because the caller of the RPC that led to that function call (`CreateTree`) would consider it a failed precondition.

**Comment by codingllama** [comment]
Fair enough. I'll have a go at it soon-ish. :)
