### ISSUE TITLE
Bug while go build ./...

### ISSUE THREAD

**Issue by Mantas96** [google/trillian#525]
Getting error server/main.go:81: undefined: expvar.Handler while building code.
![image](https://cloud.githubusercontent.com/assets/27300676/24923766/48c1efc6-1efb-11e7-8159-e443aedb3f13.png)

**Comment by rmhrisk** [comment]
@Mantas96 can you provide the steps you followed prior to `go build`?

**Comment by daviddrysdale** [comment]
Could you check your Go version?  I believe we need 1.8 since around commit ece7b353

**Comment by Mantas96** [comment]
Followed:
go get github.com/google/trillian
cd $GOPATH/src/github.com/google/trillian
go get -t -u -v ./...
go build ./...
go test ./...

Go version: 1.7.2 Recommended was 1.7 so I assumed 1.7.2 was good enough.

**Comment by rmhrisk** [comment]
@Mantas96 can you try 1.8

**Comment by daviddrysdale** [comment]
I've updated the README for the 1.8 requirement -- sorry we missed that.

If upgrading to Go 1.8 doesn't solve the problem, please re-open.
