### ISSUE TITLE
CT: get-entries fails if there are less entries returned than requested

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#530]
In a log that has a tree size of 1 the request `get-entries?start=0&end=49` will fail with the error `backend GetLeavesByIndex request failed: rpc error: code = Unknown desc = len(ret): 1, want 50`.

This shouldn't be a failure case and should just return whatever amount was returned, in [`storage/mysql/log_storage.go:L457`](https://github.com/google/trillian/blob/3eef56129ebbbe99bed6794dc1b2c0ef31f4c98d/storage/mysql/log_storage.go#L457) the test should probably be `got > want` instead of `got != want` to prevent too much being returned but ignore the case where less than expected was.

**Comment by rolandshoemaker** [comment]
Hrm, I think I actually have a flawed understanding of current existing implementations, for some reason I thought the current Google logs allowed this but from testing it looks like they do not. Seems reasonable to expect the client to know the current size of the log when requesting entries, closing!

**Comment by pphaneuf** [comment]
For what it's worth, the open source server has no problem with that kind of request, as per this section of the RFC:

> Logs MAY honor requests where 0 <= "start" < "tree_size" and "end" >= "tree_size" by returning a partial response covering only the valid entries in the specified range.
