### ISSUE TITLE
No test files

### ISSUE THREAD

**Issue by Mantas96** [google/trillian#553]
After ''go build ./...'' command received no output on command line nor the errors but go test ./... command brought out that there are no test files.  
![image](https://cloud.githubusercontent.com/assets/27300676/25350332/6da9447e-292d-11e7-80f3-c94546afbfeb.png)

**Comment by daviddrysdale** [comment]
`[no test files]` is the normal output for subdirectories that have no `*_test.go` files, so nothing to worry about there.

However, looking at your output I suspect you need to [setup MySQL](https://github.com/google/trillian#mysql-setup) for the tests.
