### ISSUE TITLE
Map: Use "ExpectedMapRevision" in SetLeaves to kill race conditions. 

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#559]
A mapper's current operational cycle looks like:
- ReadLeaves
- Apply mutations
- SetLeaves

If two mappers are running at the same time for redundancy, they may trample each other's SetLeaves operations. To eliminate this, propose including an `expected_map_revision` field in the SetLeaves API which will cause the whole operation to fail if there already exists a SignedMapHead for the given revision.

**Comment by Martin2112** [comment]
Is this complete now?

**Comment by Martin2112** [comment]
Ping.

**Comment by gdbelvin** [comment]
This work has not been started.

**Comment by Martin2112** [comment]
OK. I assume it's still relevant? I'm just having a quick pass through to find things that are done or no longer needed.

**Comment by gdbelvin** [comment]
Yep, still needed.
