### ISSUE TITLE
CT: leaf_input truncated if > 65,535 bytes

### ISSUE THREAD

**Issue by grahamedgecombe** [google/trillian#596]
The MySQL schema stores the `LeafValue` and `ExtraData` in a `BLOB`, so they're silently truncated if they're over 65,535 bytes.

I think this is causing problems with Let's Encrypt's test CT log, which I believe runs Trillian. The `leaf_input` of entry 6984671 (http://clicky.ct.letsencrypt.org/ct/v1/get-entries?start=6984671&end=6984671) has been truncated to exactly 65,535 bytes despite the certificate being much longer - the 10k bad SANs cert from https://10000-sans.badssl.com/.

This also causes Trillian to produce invalid Merkle tree hashes as the `leaf_input` hash is calculated before MySQL ends up truncating the `leaf_input`, whereas monitors will compute the hash of the truncated entries. (I think this is ultimately causing mine to mark every Let's Encrypt Clicky STH as invalid - see https://ct.grahamedgecombe.com/logs/38.)

The `ASN1.Cert` structure in RFC 6962 has a 3 byte length so it can be up to 16 megabytes. However, a `MEDIUMBLOB` still isn't enough in the worst case as a few extra bytes are consumed by the timestamp/entry type, so the schema probably needs to use `LONGBLOB` instead (or reject submissions which are too long, though I don't know whether this would be considered acceptable under the current Chrome policy).

**Comment by rolandshoemaker** [comment]
I believe Trillian already tries to protect against this by setting [`GLOBAL sql_mode = 'STRICT_ALL_TABLES'`](https://github.com/google/trillian/blob/master/storage/mysql/storage.sql#L10) which should throw an error when a field may be truncated due to overflowing the field size.

When setting up clicky I may have, uh, disabled that for debugging purposes and forgotten to turn it back on which caused these truncated entries and invalid STHs. Luckily the point of clicky was to test deploying Trillian so I think we'll probably just freeze it and roll over to a new log where `STRICT ALL TABLES` is enabled.

It probably does make sense to move up to `LONGBLOB` though as things like the 10,000 SAN cert do exist and we should probably support logging them.

**Comment by rolandshoemaker** [comment]
It is also possible that the `sql_mode` var could be set on a per-session basis in order to prevent foot-gunning like what happened to clicky but I'm not sure that is 100% necessary...

**Comment by AGWA** [comment]
Out of curiosity, would it be possible for the log to recover from this error by retroactively fixing the LeafInput for this entry (after first changing the column type), or has it signed STHs that are now inconsistent?

**Comment by AGWA** [comment]
To clarify my question, when Trillian signs a new STH, does it read and re-hash entries to calculate the new root hash, or does it use the hashes already in the Merkle Tree?  If it reads and re-hashes entries, then the log is toast.  If it uses the hashes already in the Merkle Tree, then the STHs would be consistent, making this a recoverable error.

I'm curious mainly from a policy perspective - if this were to happen to a production log, would that log be toast or could it patch things up and continue operating?

**Comment by AlCutter** [comment]
@AGWA, it uses the hashes already in the tree so it's, um, "ok" :grimacing:

**Comment by rolandshoemaker** [comment]
> @AGWA, it uses the hashes already in the tree so it's, um, "ok" :grimacing:

Interesting... so in theory if I had the DER of the pre-truncated certificate and fixed it in the DB that would technically 'fix' the problem for anyone who hadn't already retrieved that leaf? (I don't think we'll actually do this, rolling a new log is good practice for now, but it's an interesting solution)

**Comment by AlCutter** [comment]
Currently, yup, although the log should really be verifying correctness of _things_ as they leave too, and longer term we've thought a little about a background `fsck` to look for badness - either of those could've caught this (although only after-the-fact).

**Comment by rolandshoemaker** [comment]
Cool, I'd have to go dig through my logs but I do remember seeing something along the lines of `received malformed leaf from backend` in the CT personality front end which probably should've tipped me off but I was about to get on a plane so `¯\_(ツ)_/¯`.

**Comment by Martin2112** [comment]
Nobody will ever need more than 64 kbytes of Certificates!

I'll add this to the next volume of "Unhelpful Database Behaviour".

Martin

On 9 May 2017 at 18:14, Roland Bracewell Shoemaker <notifications@github.com

**Comment by Martin2112** [comment]
BTW the data type change is not a complete fix as there are server and client limits that will also need to be adjusted. https://dev.mysql.com/doc/refman/5.7/en/packet-too-large.html
