### ISSUE TITLE
CT: support STH pollination to detect database inconsistency

### ISSUE THREAD

**Issue by AGWA** [google/trillian#600]
A great robustness feature would be for the CT personality to exchange STHs with STH pollination servers.  If an STH pollination server knows about an STH that is inconsistent with the log's own view, it means there has been database corruption.  Ideally, the log would immediately shut down and give the operator a chance to recover before the log signs an inconsistent STH.

If Venafi's log had this feature, its disqualification would have been avoided.

**Comment by pavelkalinnikov** [comment]
Closing this. It should live in the CT repo. So far, we have some work on this internally.
