### ISSUE TITLE
CT: Allow configuration of acceptable EKUs

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#606]
Currently `x509.ExtKeyUsageAny` is used in `x509.VerifyOptions` which means any EKU will be accepted (including i.e. S/MIME or code signing certs that cannot be used for server auth). For production CA use we would most likely want to restrict submitted certificates to those that can be used for server authentication so we'd want to just set `x509.ExtKeyUsageServerAuth`.

I think there is some value in being able to fine tune this to some degree (beyond just flipping a all/server-auth only switch) but how to allow configuring this can get a little complicated.

**Comment by Martin2112** [comment]
Closed via #616.
