### ISSUE TITLE
Ensure Trillian Log core allows dupes

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#619]
Some storage layers may guarantee no two leaves can share the same `LeafIdentityHash` or `MerkleLeafHash` by enforcing this at `QueueLeaves` time, but there are other classes of storage implementation we'd like Trillian to support where this would be hard, if not impossible, to implement.

Trillian Log APIs and core code should not assume that dupes will be disallowed by storage, and must cope with cases where duplicate entries exist both within the to-be-sequenced queue as well as the sequenced leaves.

**Comment by AlCutter** [comment]
Required for #609

**Comment by pphaneuf** [comment]
Duplicate identity hashes, but duplicate leaf hashes too?

**Comment by AlCutter** [comment]
You wouldn't normally expect it to occur, but the commit queue architectures which aren't able to detect and squash it in the commit queue can't prevent it, so: imagine a bug where a personality submits the same leaf twice somehow, if those go to different Trillian FEs they can't detect the dupe, so the leaves both make it into the unsequenced queue, now they've got* to be integrated...

*It _could_ be worked around with increased complexity during dequeuing, but it's not clear that's a sensible trade-off at the moment.

**Comment by pphaneuf** [comment]
Right, while it's safer for spamming purposes to detect duplicates as best we can, it should be safe to have *some* duplicates of both kinds, true.
