### ISSUE TITLE
Map: Specify index length in tree config

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#640]
All indexes in a particular map must all the same length. 
This length is distinct and unrelated to the hashing strategy. 
This length is currently being set to a constant, but could be a configurable option for each map.

**Comment by Martin2112** [comment]
I'm suggesting we close this and reopen wen we've got a requirement for different lengths? Unless you expect this to come up soon in KT?

**Comment by gdbelvin** [comment]
Sounds good.
