### ISSUE TITLE
Default mysql database name and username are conflict prone

### ISSUE THREAD

**Issue by AMarcedone** [google/trillian#658]
The default username and database name for the trillian mysql db are currently both test. This can be confusing and easily cause conflicts with other databases on the host machine.
I am happy to submit a pull reques substituting "test:zaphod@tcp(127.0.0.1:3306)/test" with "testTrillianUser:testTrillianUserPwd@tcp(127.0.0.1:3306)/testTrillianDB" (and related changes).

**Comment by codingllama** [comment]
No objections on my part. I'm not that found on that many things being called "test" either. :)

Ideally, #456 would "solve" this for unit tests. Integration test scripts could have a parameter for the DB URL, which solves the whole user/pass/database/schema issue at once, with the default being whatever Travis needs. That's my 2c, though; not sure where the rest of the team stands.

**Comment by Martin2112** [comment]
I don't think we have time to work on this at the moment but don't have objections to changing it and would be willing to take PRs to improve it.
