### ISSUE TITLE
Create Example Cloud Deployment Scripts

### ISSUE THREAD

**Issue by witoff** [google/trillian#666]
Deploying Trillian should be as simple as possible for new users, particularly in AWS and GCP environments.  In each environment, example deployments should be created with Terraform to provide codified, quick-to-launch playbooks.  Deployment in each cloud should use:

**Google Cloud Platform**
* Backend: Use [CloudSQL](https://cloud.google.com/sql/)'s MySQL engine
* Application: GCE

**AWS**
* Backend: Use [aurora](https://aws.amazon.com/rds/aurora/)'s MySQL compatibile engine.
* Application: EC2

In either deployment, Trillian, should be tested and any incompatibilities with these environments treated as bugs.

Since different production environments may differ substantially, this should be documented with runnable scripts within the `/examples/` directory and end-users are expected to tailor their own production deployments.

**Comment by Martin2112** [comment]
Can this be closed or is there more to be done?

**Comment by daviddrysdale** [comment]
Close for now, please re-open if there's more to do.
