### ISSUE TITLE
go get -u ./... will prompt an error saying "undefined: metadata.FromContext"

### ISSUE THREAD

**Issue by juniway** [google/trillian#807]
error message: 
```
vendor/github.com/coreos/etcd/proxy/grpcproxy/watch.go:107: undefined: metadata.FromContext
vendor/github.com/grpc-ecosystem/grpc-gateway/examples/server/a_bit_of_everything.go:136: undefined: metadata.FromContext
```

this is due to an update to the package google.golang.org/grpc/metadata on 2017/8/18, this update deletes the deprecated function `FromContext()` and thus only `FromIncomingContext()` can be used.

original commit message from google.golang.org/grpc
```
Revision: 596a6acc87c73c3bc398a60ef0089976491ca060
Author: dfawley <dfawley@google.com>
Date: 2017/8/18 4:10:28
Message:
metadata: Remove NewContext and FromContext for gRFC L7 (#1392)
```

**Comment by daviddrysdale** [comment]
This works OK for me -- can you confirm your tree is up-to-date with commit b144701e2c85ba911cd135dde39a427e653154cb and commit a1b0c2d64958c7d71e38eb08ad7aafabc0638be3 ?

**Comment by juniway** [comment]
@daviddrysdale yes, my tree is up-to-date, as pointed out in the error message, `watch.go` and `a_bit_of_everything.go` still refer to the removed function.

**Comment by daviddrysdale** [comment]
Ah, I'm running with a Go 1.9 release candidate and it [ignores vendor dirs for ./...](https://tip.golang.org/doc/go1.9#vendor-dotdotdot) -- that explains the difference.

**Comment by codingllama** [comment]
If you are using bash, the monster below ought to be *somewhat* equivalent to Go's 1.9 `go get`:

```bash
go get . && ls -d */ | tr -d '/' | grep -v vendor | while read d; do go get ./$d/...; done
```

In human-readable terms, just do `go get ./$package/...` for every dir but vendor/.

**Comment by juniway** [comment]
@codingllama that makes sense
