### ISSUE TITLE
Logverifier: return a set of known errors

### ISSUE THREAD

**Issue by Liamsi** [google/trillian#815]
For the key-transparency monitor it would be useful if the [`client.LogVerifier`](https://github.com/google/trillian/blob/d813430f0bd1a0e8cc72879658da034e02e2c1fd/client/verifier.go#L46-L73) returned a list of exported errors to let callers know which part of the verification failed (without parsing the returned error strings). 
A kt-monitor could then decide how to deal with these different errors and how to publish them. 

A good start could be: 
`ErrInvalidLogConsistencyProof = errors.New("invalid log consistency proof")`,  `ErrInvalidLogSignature = errors.New("invalid signature on log root")`)

On another note it would be great if there was an map equivalent `MapVerifier`.

**Comment by Martin2112** [comment]
I think this may be obsolete now as the client was changed. There is a specific error for invalid signature in the `VerifySignedLogRoot` code.
