### ISSUE TITLE
Facilitate upgrades

### ISSUE THREAD

**Issue by FiloSottile** [google/trillian#837]
Yesterday the SD card running behindthesofa experienced metaphorical self-combustion, so I had to rebuild the entire system. Since vendoring is not complete making builds unreproducible (separate issue), I had to build from master. The last time I decided to update Trillian I had a similar experience.

* Not knowing what changes would affect me I had to eyeball a hundred commits. Nothing seemed breaking.
* I was wrong. Checking the history of `storage.sql` I found half a dozen changes I had to apply.
* Checking the history of `.proto` files suggested a ENUM lost some values, which I decided to ignore because repacking protobufs is hard, and there's probably (?) no need here. (Last time I had to repack.)
* Trying to start the services revealed that the format for ct_server config files changed.
* ~A few hours later I discovered `max_root_duration` is now off by default. Now trying to re-enable it.~ I was wrong, but took forever to realize.

The very minimum would be a CHANGELOG of breaking changes. ALTER TABLE hints would be useful. Migrations would be excellent.

**Comment by codingllama** [comment]
Thanks for the report (and patience!), Filippo.

We discussed DB updates a few times; I remember suggesting that we version scripts and provide incremental updates, but it didn't "catch on" so far.

Re lost enum values: are you talking about [Tree deletion states](https://github.com/google/trillian/blob/master/trillian.proto#L71) or is it something else? If it's the former that's a safe change, those values weren't used outside of tests. If it's something else I'd like to know, as removed enums _may_ cause problems depending on the circumstances.

I defer to @AlCutter on actual next steps for the team (CHANGELOG, incremental DB updates, etc).

**Comment by Martin2112** [comment]
You're right we haven't done enough on this. I just went through and created releases for each major development point and then with a log of visible changes for each release since 1.0. This should indicate what's changed from the point of view of upgrading. Let me know if you find anything important missing.

We'll try to do more in future.

**Comment by daviddrysdale** [comment]
We now have release notes that cover API and DB changes.
