### ISSUE TITLE
Flakiness in creating trees for tests

### ISSUE THREAD

**Issue by daviddrysdale** [google/trillian#856]
Recent Travis builds are sometimes hitting errors with the RPCs used to create test trees.

E.g.
```
admin_integration_test.go:524: CreateTree() returned err = rpc error: code = Unavailable desc = grpc: the connection is unavailable
```
or 
```
F1003 13:06:31.845616    6888 main.go:161] Failed to create tree: rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

**Comment by daviddrysdale** [comment]
This is still causing problems for Travis runs of unit tests (which use CreateTree internally and so don't pick up the retry added in #857)

**Comment by Martin2112** [comment]
Fixed yet?

**Comment by daviddrysdale** [comment]
Not seen it for a while, let's close this.
