### ISSUE TITLE
Extend hammer tools to write an operations logfile that can be used to replay a hammer run

### ISSUE THREAD

**Issue by phad** [google/trillian#863]
In theory if you rebuild the hammer at a known commit and use the same PRNG seed it will then perform the exact same run.

In practice it's not that simple!  The hammer behavior is also tuned by flags that let you set Biases and the probability of performing invalid operations.  If goroutines were used internally then deterministic re-runs would likely be impossible.

The hammer tools do a great job of performing soak tests on a log/map but could do more to assist later investigation if the tests reveal a bug in the log/map being hammered.

This issue proposes extending the tools to write an operations log file which contains enough info to conduct an accurate replay of the hammer run later on.

For the map, this seems more straightforward as each SetLeaves causes a new tree revision and SignedMapRoot to be created.  I'm not sure if for a Log it would be that simple, as the Log's signer may not kick in in a predictable way.

The maphammer should write to its operation log at start-up:
  - the initial state of the map (at minimum, if it is empty or not)
     + if the maphammer uses a clean/empty map - maybe one created by the tool itself - that would be ideal
  - the random seed
  - the end-point biases and 'invalid operation' flags
 
Then as the tool proceeds to hammer the map, it should write for each hammering operation:
 - the endpoint selected;
 - the choices made for valid/invalid ops
 - the request proto sent to the Map API
 - the response proto received from the Map API
 - the validation status of the response including where expectations failed

**Comment by Martin2112** [comment]
Is this being actively worked on? I'm having a tidy up.

**Comment by phad** [comment]
Not, it's not.
