### ISSUE TITLE
Map Storage tests have difficulties on SQLlite

### ISSUE THREAD

**Issue by phad** [google/trillian#896]
example:

$ go test ./storage/mysql/... -args -test.v=1 -v=4 -alsologtostderr
<snip>
=== RUN   TestLatestSignedMapRoot
--- FAIL: TestLatestSignedMapRoot (5.00s)
panic: Failed to delete rows in Unsequenced: database is locked [recovered]
	panic: Failed to delete rows in Unsequenced: database is locked

goroutine 954 [running]:
testing.tRunner.func1(0xc4205af2c0)
	/usr/lib/google-golang/src/testing/testing.go:711 +0x2d2
panic(0xa8bea0, 0xc4205b2790)
	/usr/lib/google-golang/src/runtime/panic.go:491 +0x283
github.com/google/trillian/storage/mysql.cleanTestDB(0xc4200cd5e0)
	/usr/local/google/home/hadfieldp/go/src/github.com/google/trillian/storage/mysql/storage_test.go:237 +0x2ec
github.com/google/trillian/storage/mysql.TestLatestSignedMapRoot(0xc4205af2c0)
	/usr/local/google/home/hadfieldp/go/src/github.com/google/trillian/storage/mysql/map_storage_test.go:469 +0x42
testing.tRunner(0xc4205af2c0, 0xb8a390)
	/usr/lib/google-golang/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/google-golang/src/testing/testing.go:789 +0x2de
FAIL	github.com/google/trillian/storage/mysql	13.337s

**Comment by phad** [comment]
Seemingly related:

$ go test ./storage/mysql/... -args -test.v=1 -v=2 -alsologtostderr
<snip>
=== RUN   TestNodeRoundTrip
I1116 11:46:08.977860  156827 storage_test.go:156] Node to store: {[0] 8}
I1116 11:46:08.977889  156827 storage_test.go:156] Node to store: {[1] 8}
I1116 11:46:08.977895  156827 storage_test.go:156] Node to store: {[2] 8}
I1116 11:46:08.977902  156827 storage_test.go:156] Node to store: {[3] 8}
I1116 11:46:08.978418  156827 subtree_cache.go:381] Creating new empty subtree for , with depth 8
W1116 11:46:08.978510  156827 tree_storage.go:315] Failed to set merkle subtrees: NOT NULL constraint failed: Subtree.SubtreeId
W1116 11:46:08.978518  156827 tree_storage.go:389] TX commit flush error: NOT NULL constraint failed: Subtree.SubtreeId
--- FAIL: TestNodeRoundTrip (0.11s)
	storage_test.go:65: Failed to commit nodes: NOT NULL constraint failed: Subtree.SubtreeId

**Comment by codingllama** [comment]
Sorry for the flakiness. You could try setting TRILLIAN_SQL_DRIVER=mysql while we figure out how to improve it.

Out of curiosity, OS X or linux?

**Comment by phad** [comment]
It's Ubuntu Trusty.

@gdbelvin tells me that the 'databased is locked' issue is known already in the map code, and is likely to be caused by SQLite's table-level locking and the Map's use of multiple transactions when lots of values are being modified.

I'm about to push a commit that Skip()'s the affected tests for !mysql as a temp measure.

I don't know what to make of the second (NULL SubTreeID) failure though.  Do you have any ideas there?

**Comment by codingllama** [comment]
Yes, map integration tests, for example, are known to not work. IMO that's OK, as we want integration tests to run against MySQL (and do things that would break sqlite guarantees too). I expected plain storage tests to work, though, so I'm a bit disappointed.

I'm unsure about the "NULL SubTreeID", but if there's concurrency in play I wouldn't be surprised to see sqlite errors like that.

**Comment by Martin2112** [comment]
I think we can close this. SQLlite is not appropriate for these tests and probably can't be made to work.
