### ISSUE TITLE
Clarify in Map API whether it should be possible to delete stored values by SetLeave with index and empty value

### ISSUE THREAD

**Issue by phad** [google/trillian#899]
The maphammer's `hammer.go` code in `setLeaves` with choice `DeleteLeaf` suggests this should be possible.

However `SetLeaves` in the map server's `map_rpc_server.go` deliberately skips any leaf with empty value.  There's a comment stating: "Leaves are empty by default. Do not allow clients to store empty leaf values as this messes up the calculation of empty branches."

Consequently the maphammer is unable to delete leaves.  I don't understand why this doesn't cause it to fail in Travis, as there are no flags set that would inhibit the maphammer from trying this.

**Comment by phad** [comment]
Once the design intent of the API is clarified, this needs to be documented and then enforced in tests.

**Comment by daviddrysdale** [comment]
I think this was covered by #1278
