### ISSUE TITLE
trillian_map_server : MySQL error 'Could not start tree TX: Error 1040: Too many connections' when running examples/ct_mapper

### ISSUE THREAD

**Issue by musalbas** [google/trillian#901]
The example instructions for setting up a CT mapper don't seem to work. https://github.com/google/trillian/tree/master/examples/ct/ctmapper

I had to use these commands instead to get it to start:

```# Ensure you have your MySQL DB set up correctly, with tables created by the
# contents of storage/mysql/storage.sql
yes | scripts/resetdb.sh

go build ./server/trillian_map_server
go build ./examples/ct/ctmapper/mapper
go build ./examples/ct/ctmapper/lookup

# in one terminal:
./trillian_map_server --logtostderr

# in another (leaving the trillian_map_server running):
go build ./cmd/createtree/
tree_id=$(./createtree \
    --admin_server=localhost:8090 \
    --signature_algorithm=ECDSA
    -tree_type MAP
    -hash_strategy TEST_MAP_HASHER)
./mapper \
    -source http://ct.googleapis.com/pilot \
    -map_id=${tree_id} \
    -map_server=localhost:8090 \
    --logtostderr
```

The problems are:
1. You need to specify the tree type to ./createtree.
2. MapHasher(RFC6962_SHA256) is an unknown hasher. Only TEST_MAP_HASHER works.
3. The HTTP server on port 8091 does not work; you get `rpc error: code = Unavailable desc = transport is closing`. Only port 8090 works.

I'm not sure if these are bugs in Trillian itself, or there's a missing step in the instructions?

Also due to these errors, I had to increase the max number of MySQL connections - the batches open hundreds of idle connections before committing it seems.
```I1127 12:31:14.634811    9532 mapper.go:174] Got 490 values, and 490 proofs
I1127 12:31:14.634820    9532 mapper.go:176] Storing updated map values for domains...
W1127 12:31:15.267977    9532 mapper.go:233] mapper run failed: rpc error: code = Unknown desc = Error 1040: Too many connections
```

**Comment by codingllama** [comment]
Hey Mustafa, thanks for the detailed report.

It does sound like some of it is due to outdated documentation. I'll give it a try and see what I can make of it.

**Comment by codingllama** [comment]
OK, I got it working after a while. The secret is setting is setting a small `--log_batch_size` in `mapper` so the server copes with the requests. Eg:

```bash
./mapper
    --logtostderr \
    --log_batch_size=10 \
    --map_id=${tree_id} \
    --map_server=localhost:8090 \
    --source http://ct.googleapis.com/pilot
```

There's definitely a problem with trillian_map_server, though, as it clearly breaks the connection pool on larger requests. I'm copying @gdbelvin and @phad here as map experts.

Gary / Paul: you can follow the instruction on how to run CT Mapper, without setting --log_batch_size, to repro the problem. I tried limiting the max # of connections with a manual edit to trillian_map_server, which just makes the server hang, so I think this may require more than just a connection limit.

Btw, see #902 for the updated documentation.

**Comment by phad** [comment]
I've repro'd the 'Too many connections' issue with --log_batch_size=10.

```
$ yes | scripts/resetdb.sh 
Warning: about to destroy and reset database 'test'
Resetting DB...
Reset Complete

$ go build ./server/trillian_map_server

$ go build ./examples/ct/ctmapper/mapper

$ go build ./examples/ct/ctmapper/lookup

$ go build ./cmd/createtree

$ tree_id=$(./createtree  --admin_server=localhost:8090 --tree_type=MAP --hash_strategy=TEST_MAP_HASHER)

$ echo $tree_id
7905880401743917650

$ ./mapper --logtostderr --log_batch_size=10 --map_id=${tree_id} --map_server=localhost:8090 --source=http://ct.googleapis.com/pilot
I1129 11:37:28.378168  122111 mapper.go:78] starting mapping batch
I1129 11:37:28.390968  122111 mapper.go:97] Fetching entries [1, 11] from log
I1129 11:37:29.215370  122111 mapper.go:140] Found 15 unique domains from certs
I1129 11:37:29.215404  122111 mapper.go:141] Fetching current map values for domains...
*snip*
I1129 11:37:29.258442  122111 mapper.go:174] Got 15 values, and 15 proofs
I1129 11:37:29.258459  122111 mapper.go:176] Storing updated map values for domains...
I1129 11:37:29.326714  122111 mapper.go:205] Set resp: map_root:<timestamp_nanos:1511955449321526853 root_hash:"\t\340\237\273\006\314\205O2d\353\307\324h\251ta\317HW\274\317\335\355?\277\251\353]\200\337\346" signature:<hash_algorithm:SHA256 signature_algorithm:ECDSA signature:"0F\002!\000\342'pl\235(Z\022\023P\376\200r\t\272\232K\306d\024\271.k\210%\r\352\353\306c\r\017\002!\000\260\200Xl*]V\265\035\024|o\226\364\013K\321?\036\3051\351\273\345X\013\320\266\005\374\243\316" > map_id:7905880401743917650 map_revision:1 metadata:<type_url:"type.googleapis.com/ctmapperpb.MapperMetadata" value:"\020\013" > > 
I1129 11:37:29.326812  122111 mapper.go:207] Map run complete, took 0.9 secs to update 16 values (16.87/s)
I1129 11:37:29.326828  122111 mapper.go:78] starting mapping batch
I1129 11:37:29.328665  122111 mapper.go:97] Fetching entries [12, 22] from log
I1129 11:37:30.048383  122111 mapper.go:140] Found 30 unique domains from certs
*snip*
I1129 13:01:53.290455  122111 mapper.go:168] Got ctmapperpb.EntryList{Domain:"", CertIndex:[]int64(nil), PrecertIndex:[]int64(nil)}
I1129 13:01:53.290468  122111 mapper.go:172] will update for 
I1129 13:01:53.290478  122111 mapper.go:174] Got 385 values, and 385 proofs
I1129 13:01:53.290491  122111 mapper.go:176] Storing updated map values for domains...
W1129 13:01:53.468693  122111 mapper.go:233] mapper run failed: rpc error: code = Unknown desc = Error 1040: Too many connections
I1129 13:01:58.468924  122111 mapper.go:78] starting mapping batch
*snip*
I1129 13:25:42.737440  122111 mapper.go:168] Got ctmapperpb.EntryList{Domain:"", CertIndex:[]int64(nil), PrecertIndex:[]int64(nil)}
I1129 13:25:42.737454  122111 mapper.go:172] will update for 
I1129 13:25:42.737465  122111 mapper.go:174] Got 385 values, and 385 proofs
I1129 13:25:42.737479  122111 mapper.go:176] Storing updated map values for domains...
W1129 13:25:42.869212  122111 mapper.go:233] mapper run failed: rpc error: code = Unknown desc = Error 1040: Too many connections
I1129 13:25:47.869441  122111 mapper.go:78] starting mapping batch
I1129 13:25:47.872625  122111 mapper.go:97] Fetching entries [87935, 87945] from log
I1129 13:25:48.043393  122111 mapper.go:140] Found 385 unique domains from certs
I1129 13:25:48.043424  122111 mapper.go:141] Fetching current map values for domains...

meanwhile...

$ ./trillian_map_server --logtostderr
I1129 11:34:11.047237  120938 quota.go:98] Using QuotaManager *mysqlqm.QuotaManager
I1129 11:34:11.047807  120938 main.go:96] HTTP server starting on localhost:8091
I1129 11:34:11.047836  120938 main.go:108] RPC server starting on localhost:8090
I1129 11:34:11.048342  120938 main.go:117] Deleted tree GC started
I1129 11:37:29.255932  120938 map_rpc_server.go:191] 7905880401743917650: wanted 15 leaves, found 0
*snip*
I1129 13:01:44.059920  120938 map_rpc_server.go:191] 7905880401743917650: wanted 385 leaves, found 0
W1129 13:01:44.244830  120938 tree_storage.go:147] Could not start tree TX: Error 1040: Too many connections
I1129 13:01:53.208786  120938 map_rpc_server.go:191] 7905880401743917650: wanted 385 leaves, found 0
W1129 13:01:53.462186  120938 tree_storage.go:147] Could not start tree TX: Error 1040: Too many connections
I1129 13:02:02.328907  120938 map_rpc_server.go:191] 7905880401743917650: wanted 385 leaves, found 0
*snip*
-------

**Comment by phad** [comment]
Complete server log here: https://gist.github.com/phad/872ce56feb7ed3f385983009f3212248

**Comment by phad** [comment]
It's notable that the 'too many connections' error first manifests when the server log shows an order-of-magnitude increase in the number of leaves being touched, going from "wanted ~15-40 leaves" up to "wanted 385 leaves".

I1129 13:01:23.789093  120938 map_rpc_server.go:191] 7905880401743917650: wanted 17 leaves, found 0
I1129 13:01:24.565746  120938 map_rpc_server.go:191] 7905880401743917650: wanted 15 leaves, found 0
I1129 13:01:25.173171  120938 map_rpc_server.go:191] 7905880401743917650: wanted 18 leaves, found 0
I1129 13:01:26.050872  120938 map_rpc_server.go:191] 7905880401743917650: wanted 17 leaves, found 0
I1129 13:01:26.707871  120938 map_rpc_server.go:191] 7905880401743917650: wanted 18 leaves, found 0
I1129 13:01:27.822828  120938 map_rpc_server.go:191] 7905880401743917650: wanted 27 leaves, found 0
I1129 13:01:28.991467  120938 map_rpc_server.go:191] 7905880401743917650: wanted 40 leaves, found 0
I1129 13:01:30.196014  120938 map_rpc_server.go:191] 7905880401743917650: wanted 39 leaves, found 0
I1129 13:01:31.115716  120938 map_rpc_server.go:191] 7905880401743917650: wanted 24 leaves, found 0
I1129 13:01:31.890482  120938 map_rpc_server.go:191] 7905880401743917650: wanted 17 leaves, found 0
I1129 13:01:33.428234  120938 map_rpc_server.go:191] 7905880401743917650: wanted 19 leaves, found 0
I1129 13:01:34.221167  120938 map_rpc_server.go:191] 7905880401743917650: wanted 19 leaves, found 0
I1129 13:01:34.938394  120938 map_rpc_server.go:191] 7905880401743917650: wanted 17 leaves, found 0
I1129 13:01:35.673687  120938 map_rpc_server.go:191] 7905880401743917650: wanted 18 leaves, found 0
I1129 13:01:36.546482  120938 map_rpc_server.go:191] 7905880401743917650: wanted 24 leaves, found 0
I1129 13:01:37.355405  120938 map_rpc_server.go:191] 7905880401743917650: wanted 25 leaves, found 0
I1129 13:01:38.486643  120938 map_rpc_server.go:191] 7905880401743917650: wanted 19 leaves, found 0
I1129 13:01:39.436084  120938 map_rpc_server.go:191] 7905880401743917650: wanted 19 leaves, found 0
I1129 13:01:40.149692  120938 map_rpc_server.go:191] 7905880401743917650: wanted 19 leaves, found 0
I1129 13:01:44.059920  120938 map_rpc_server.go:191] 7905880401743917650: wanted 385 leaves, found 0
W1129 13:01:44.244830  120938 tree_storage.go:147] Could not start tree TX: Error 1040: Too many connections
I1129 13:01:53.208786  120938 map_rpc_server.go:191] 7905880401743917650: wanted 385 leaves, found 0
W1129 13:01:53.462186  120938 tree_storage.go:147] Could not start tree TX: Error 1040: Too many connections
I1129 13:02:02.328907  120938 map_rpc_server.go:191] 7905880401743917650: wanted 385 leaves, found 0
W1129 13:02:02.530960  120938 tree_storage.go:147] Could not start tree TX: Error 1040: Too many connections
I1129 13:02:11.475483  120938 map_rpc_server.go:191] 7905880401743917650: wanted 385 leaves, found 0
W1129 13:02:11.673773  120938 tree_storage.go:147] Could not start tree TX: Error 1040: Too many connections

**Comment by gdbelvin** [comment]
Thats an interesting finding.  It might have to do with the way the map
fires off up to 256 connections to the database in parallel.
Do we know what the upper limit on database connections might be?  We may
want to investigate an worker-pool based architecture for the subtree
builders.

-G

**Comment by phad** [comment]
I'm thinking of building a repro case for this, to strip out as much of the map server as possible.
At first sight it looks like we have:
 * mapstorage.BeginForTree
 * 385x mapstorage.mapTreeTx.PrepareContext
 * 385x sql.ExecContent
 * mapTreeTx.StoreSignedMapRoot
 * mapTreeTx.Commit
and interleaved in all that, via the SparseMerkleTreeWriter, some number (*) of
 * mapstorage.BeginForTree
 * tx.GetMerkleNodes
 * tx.SetMerkleNodes
 * tx.Commit

* not sure how many times this sequence will be called.

**Comment by gdbelvin** [comment]
That later sequence is called potentially up to 2^88 times and up to 2^80 times in parallel.  
Each [level](https://github.com/google/trillian/blob/07a54b9d51bf340f4136a1a7e10b702ac5cca810/storage/mysql/map_storage.go#L60) is computed in parallel:
```
Level 1: 0 to 2^(8 * 1) 
Level 2: 0 to 2^(8 * 2)
...
Level 10: 0 to 2^(8 * 10)
```

**Comment by Martin2112** [comment]
Going to close this for the moment. If using the map the default MySQL connection limit will need to be raised. It should then work.
