### ISSUE TITLE
How to configure MySQL for trillian Log

### ISSUE THREAD

**Issue by homepc91** [google/trillian#905]
Hii,, Everyone's

Please help/guide me to install and configure MySQL for trillian Log

Thanks

**Comment by daviddrysdale** [comment]
Hi,

The project [README](https://github.com/google/trillian/blob/master/README.md) has a section on [setting up MySQL](https://github.com/google/trillian/blob/master/README.md#mysql-setup) for Trillian; for more general MySQL queries you're probably better off with the [MySQL docs](https://dev.mysql.com/doc/) or their [getting started guide](https://dev.mysql.com/doc/mysql-getting-started/en/)

Hope that helps.

**Comment by homepc91** [comment]
its not working on my system....

**Comment by homepc91** [comment]
am trying to configure on Ubuntu 16.04 and macOS 10.11
