### ISSUE TITLE
MySQL "busy buffer" implicated in test flakes

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#933]
> ok  	github.com/google/trillian/examples/ct/ctmapper/mapper	1.016s
> ?   	github.com/google/trillian/examples/vmap/trillian_map_client	[no test files]
> ?   	github.com/google/trillian/extension	[no test files]
> **[mysql] 2018/01/03 14:01:43 packets.go:450: busy buffer**
> E0103 14:01:43.221471   11359 log_operation_manager.go:452] failed to execute operation on logs: failed to retrieve full list of log IDs: failed to get tx for retrieving logIDs: context canceled
> --- FAIL: TestInProcessLogIntegration (21.26s)
> 	log_integration_test.go:106: Test failed: log inclusion index: 91 proof checks failed: GetInclusionProof(index: 91, treeSize 108): rpc error: code = Unavailable desc = transport is closing, want nil: true
> FAIL
> FAIL	github.com/google/trillian/integration	41.638s
> ok  	github.com/google/trillian/integration/admin	3.337s

Potentially related background: https://github.com/go-sql-driver/mysql/issues/314

**Comment by AlCutter** [comment]
Also possibly related: https://github.com/go-sql-driver/mysql/issues/526

**Comment by Martin2112** [comment]
Your fix looked like it might have solved this?

**Comment by Martin2112** [comment]
I think this is probably fixed. Will close for now.
