### ISSUE TITLE
Add a section about GCE/Kubernetes configs in the examples README.md

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#953]
here: https://github.com/google/trillian/tree/master/examples/deployment
So that people know about the `gce/deploy.sh` script!

**Comment by DazWilkin** [comment]
Stumbled upon the Kubernetes deployment and the reference to it (slightly confusingly) from the GCE directory. I think neither work. I'd like to help contribute to addressing this if there's interest?

I'm working through some issues as I encounter them.

With apologies (generally) for my ignorance, to what specifically should `${LOG_URL}` and `${MAP_URL}` refer?

**Comment by AlCutter** [comment]
I added some docs in the kubernetes directory a little while back, very keen to know if they work for you @DazWilkin !

The `LOG_URL` and `MAP_URL` refer to the log (and map) server `host:port` which the servers listen on once they're running - I think these are used for provisioning new trees into Trillian via the admin interface exported on the servers.

**Comment by Martin2112** [comment]
I think there's a chance that this can be closed but not sure it's completely done?
