### ISSUE TITLE
Define Canonical Representations for SignedLogRoot and SignedMapRoot

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#958]
The current `ObjectHash` based signature for the `SignedLogRoot` and `SignedMapRoot` in Trillian is not stable enough for production use. A simpler, well defined signature scheme is desired. A simpler scheme would enable:
- Signing SignedLogRoots inside Google
- General gossip
- Verifiers in other languages

The proposed canonical encoding is a TLS struct containing the relevant fields. 

[Design Doc](https://docs.google.com/document/d/1x-gsOcpxthlV2RCjmAb2vcxlpV7T1TzRD7tbOQVCzJA/edit#) 

## Backwards compatibility
This change would break backwards compatibility with existing `SignedLogRoot`s. 
However:
   - The current Trillian APIs do not support retrieving old `SignedLogRoot`s. 
   - All known clients of Trillian do not use the signature in the `SignedLogRoot`.  (Please speak up if you know of a counter example) 

Going forward, the `TreeInfo` struct will declare what signature format to use.

**Comment by gdbelvin** [comment]
After much discussion the new `SignedLogRoot` will take on the following format which allows gossip participants to forward `SignedLogRoot`s without risk of DoS.  `key_hint` should give an efficient path to looking up the correct key to use to verify the signature.  The LogID is determined by association with the public key that verified the structure. 

```proto
message SignedLogRoot {
   bytes key_hint = 1;  // Typically log_id. 
   bytes log_root = 2;
   bytes signature = 3;
}
```

The content inside `log_root` (For Trillian Logs) has the following TLS specified format.  Clients SHOULD verify the signature on `log_root` before attempting to parse this data structure.  
```
enum { v1(1), (65535)} Version;
struct {
  uint64 tree_size;
  opaque root_hash<0..128>;
  uint64 timestamp_nanos;
  uint64 revision;
  opaque metadata<0..65535>;
} LogRootV1;
struct {
  Version version;
  select(version) {
    case v1: LogRootV1;
  }
} LogRoot;
```

**Comment by AlCutter** [comment]
Fixed?
