### ISSUE TITLE
Can i use or integrate or configure trillian log with localhost CT server?? and I am getting errors.

### ISSUE THREAD

**Issue by homepc91** [google/trillian#965]
Hi, Everyone

Can i use trillian log server with localhost certificate transparency

I am executing mapper application and i am using this command :-

tree_id=$(./createtree --admin_server=localhost:8090 --tree_type=MAP --hash_strategy=TEST_MAP_HASHER) 

./mapper --logtostderr --log_batch_size=10 --map_id=${tree_id} --map_server=localhost:8090 --source=localhost:6962   

now am i am geting error:- 

I0201 10:14:34.078786   11979 mapper.go:96] Fetching entries [1, 11] from log
W0201 10:14:34.078837   11979 mapper.go:232] mapper run failed: Get localhost:6962/ct/v1/get-entries?end=11/ct/v1/get-entries?end=11&start=1: unsupported protocol scheme "localhost"
I0201 10:14:39.083329   11979 mapper.go:77] starting mapping batch
I0201 10:14:39.086266   11979 mapper.go:96] Fetching entries [1, 11] from log
W0201 10:14:39.086336   11979 mapper.go:232] mapper run failed: Get localhost:6962/ct/v1/get-entries?end=11/ct/v1/get-entries?end=11&start=1: unsupported protocol scheme "localhost"

Please Please help me 
and my ct server working good in my localhost server. Am trying to configure Trillian with my ct server.

how to configure or interate trillian log with localhost certificate transparency server.??

**Comment by gdbelvin** [comment]
Answered this question on the mailing list.
