### ISSUE TITLE
Follow CloudPlatform API guidelines

### ISSUE THREAD

**Issue by pavelkalinnikov** [google/trillian#985]
It appears that Trillian APIs diverge from best practices outlined in CloudPlatform [guidelines](https://cloud.google.com/apis/design/). It would be great to revisit the APIs and try to follow the advice.

In particular, we can improve [commenting](https://cloud.google.com/apis/design/documentation), reorganize [file structure](https://cloud.google.com/apis/design/file_structure) and (potentially) follow some [design patterns](https://cloud.google.com/apis/design/design_patterns) like "Representing Ranges", "Pagination" and "Output Fields" (the last one is part of commenting bit as well).

**Comment by pavelkalinnikov** [comment]
I will send a PR with some improvements to the Log API shortly.

**Comment by gdbelvin** [comment]
Would you mind also taking a look at the APIs in Key Transparency? 
https://github.com/google/keytransparency/tree/master/core/api

**Comment by pavelkalinnikov** [comment]
@gdbelvin Sure, happy to help with that. Can you please add an issue for me in KT? Will address it a bit later.
